### ISSUE TITLE
[BUG] MS connection when powershell module disabled

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [marticliment/WingetUI#2052] opened 2024-03-27 22:21 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

connects to microsoft domain even if powershell module disabled
see command used below:

### Steps to reproduce the issue

settings > powershell: disabled
quit app
reopen app
=> app attempts connection to go.microsoft.com by querying repos (Get-PSRepository)

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
█▀▀▀▀▀▀▀▀▀ [28 March 2024 12:12:44] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
```

### Relevant information

expectation: app shouldn't connect to MS to query powershell modules repos if powershell is disabled in settings

**Comment by marticliment** [comment] 2024-03-27 22:34
Please share your entire logs

**Comment by marticliment** [comment] 2024-03-27 23:10
> because it's too much to redact about the software i have installed (I kinda care about my online privacy). Sorry, i hope it helps. It should be easily reproductible though.
> 
> 1.

Then please redact it all, but I need to know which managers are running and which commands are they calling with which frequency, as well as the WingetUI logs, so I can see the base state of each manager and other useful info

**Comment by marticliment** [comment] 2024-03-27 23:36
At least share WingetUI Logs, there shouldn't be much to redact there, and I will be able to get advanced details about the package

**Comment by Bluscream** [comment] 2024-03-28 04:33
I was able to reproduce the bahavior without any more logs aswell

**Comment by marticliment** [comment] 2024-03-28 07:22
Hello,

I am not trying to annoy anyone by asking for logs. I have tons of issues to debug and fix, as well as other features, and I obviously have to do other things in my life. The time I have available to build WingetUI is very limited, and I don't want to waste it tweaking my pc to recreate an issue I haven't succeeded to recreate, because no one wanted to upload their logs.

I understand your concerns with privacy, but the things shown on the logs, especially WingetUI logs, will not destroy your privacy. The shown API token, which is used for WingetUI Widgets, is generated each time WingetUI is restarted. And the next big issue are paths, from which you easily can remove your username.

I am sorry, but I will not invest more time on this issue until you share your logs.

I understand that your time is precious, but so  is mine. You are facing an issue you want to get fixed, and trust me, I am willing to fix it, but I will need your collaboration to do so.

If you choose to not share your logs, I will close this issue. As said, I did not manage to recreate the issue locally.

**Comment by marticliment** [comment] 2024-03-28 08:51
Thanks!

**Closed** 2024-05-29 20:00 UTC
Labels: bug, ready-to-go
