### ISSUE TITLE
[FEATURE REQUEST] find a package's install location

### ISSUE THREAD

**Issue by booplazer111** [marticliment/WingetUI#1694] opened 2024-01-09 22:55 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

adding this will allow people to be able to open a package's install location without having to search manually.

### Describe how this new feature could help users.

sometimes apps do not have a desktop shortcuts and are not in the search menu so they are hard to find and open and you can't change the install location and this would fix this issue.

**Comment by marticliment** [comment] 2024-01-10 10:55
Duplicate of #1386

**Closed by marticliment** 2024-01-10 10:55 UTC
Labels: new-feature
