### ISSUE TITLE
[BUG] Some installers fail to install when supplying a custom location

### ISSUE THREAD

**Issue by thakyZ** [marticliment/WingetUI#1685] opened 2024-01-05 15:50 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I tried to install Git Extensions via your GUI through WinGet, and it would fail to install every time, and I was supplying a custom install directory of "D:\Tools\GitExtensions". According to an interactive install of the program, it said it was unable to access network drive at "D:/Tools/GitExtensions". Which I didn't think anything of at that moment, but it would appear the GitExtensions installer needs exclusively backslashes and not forward slashes.

### Steps to reproduce the issue

1. Set custom directory install for Git Extensions
2. Install uninteractivetly as admin or not.
3. Let the installer fail.
4. Install interactively with the custom directory
5. See dialog box after main installer starts.

### WingetUI Log

```text
https://gist.github.com/thakyZ/127a821b7f8f4f0f4d9c93e7091a83d0
```

### Package Managers Logs

```text
https://gist.github.com/thakyZ/e39e65003aa28c62f0334d84412a8276
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/950594/cb0a913c-a6a9-4edc-9ba3-5b0bce73bbdd)

**Comment by marticliment** [comment] 2024-01-06 18:57
Duplicate of https://github.com/marticliment/WingetUI/issues/1684

**Closed** 2024-01-06 18:57 UTC
Labels: bug, duplicate
