### ISSUE TITLE
[BUG] 3.0.2 - Fauly coreclr.dll

### ISSUE THREAD

**Issue by fernandog** [marticliment/WingetUI#2019] opened 2024-03-22 00:00 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Where I can get more logs other than Event Viewer from Windows 10?

BTW I also have WingetUI beta 3.0.1 on Windows 11 and it runs fine.

Faulting application name: WingetUI.exe, version: 1.0.0.0, timestamp: 0x65a80000
Faulting module name: coreclr.dll, version: 8.0.324.11423, timestamp: 0x65cd500d
Exception code: 0xc0000005
Fault offset: 0x000000000018c5e4
Faulting process ID: 0x12e8
Failed application start time: 0x01da7bea38e7d43a
Faulting application path: C:\Program Files\WingetUI\WingetUI.exe
Failing module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\coreclr.dll
Report ID: e49d38ce-e374-41d1-aaf6-5e152c7dce18
Full name of the failed package:
Application ID relative to the failed package:

### WingetUI Log

```text
Can't get logs
```

### Package Managers Logs

```text
n/a
```

**Comment by vankos** [comment] 2024-03-22 05:11
Can confirm, same problem on windows 11, had to downgrade to 2.2.0

**Comment by fernandog** [comment] 2024-03-22 12:09
> Can confirm, same problem on windows 11, had to downgrade to 2.2.0

Mine works on Windows 11, but it's an Insider release.

**Comment by marticliment** [comment] 2024-03-22 14:33
Please try installing https://dotnet.microsoft.com/es-es/download/dotnet/thank-you/runtime-desktop-8.0.2-windows-x64-installer

**Comment by marticliment** [comment] 2024-03-22 14:33
Please try installing https://dotnet.microsoft.com/es-es/download/dotnet/thank-you/runtime-desktop-8.0.2-windows-x64-installer

**Comment by Meche697** [comment] 2024-03-22 21:10
Please advise if different bug/issue ...
Windows 10, with .NET 8.0.3, updated yesterday. WingetUI does NOT launch in any profile but admin. I'm in my user profiles and I've tried to launch WingetUI with administrative privileges ... nothing happens. Nothing in task bar, no program, no nothing. If I launch under the admin account, no issues. I have not had an opportunity to test on Windows 11 as that is a new set up with only admin account.

**Comment by marticliment** [comment] 2024-03-22 21:17
Please try uninstalling .NET 8.0.3 and installing .NET 8.0.2 using the link provided in my last comment

**Comment by fernandog** [comment] 2024-03-22 22:52
> Please try uninstalling .NET 8.0.3 and installing .NET 8.0.2 using the link provided in my last comment

Worked with 8.0.2

**Comment by Meche697** [comment] 2024-03-22 23:31
> Please try uninstalling .NET 8.0.3 and installing .NET 8.0.2 using the link provided in my last comment

Will try, thank you. Funny thing is WingetUI updated .NET under admin the other day :).

**Comment by vankos** [comment] 2024-03-23 01:50
@marticliment thanks, it helped

**Comment by fernandog** [comment] 2024-03-24 02:31
> > Please try uninstalling .NET 8.0.3 and installing .NET 8.0.2 using the link provided in my last comment
> 
> Will try, thank you. Funny thing is WingetUI updated .NET under admin the other day :).

block the update of .NET 8.0.2 to avoid this issue

**Comment by 13regent** [comment] 2024-03-25 02:06
What's the easiest way to block .NET 8.0.3? I have uninstalled 8.0.3 a couple of times now and it keeps coming back?

**Comment by marticliment** [comment] 2024-03-25 08:53
I am afraid .NET gets updated via Windows Update, so I guess you could disable "Update other Microsoft Products through Windows Update" from Windows Settings, and ignore updates for .NETCore8 on WingetUI

**Comment by marticliment** [comment] 2024-03-25 08:55
Btw, next WingetUI Version will install NET 8.0.2 instead of 8.0.3. I will therefore close this issue

**Comment by marticliment** [comment] 2024-04-11 15:00
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**

**Comment by fernandog** [comment] 2024-04-25 21:57
@marticliment  sorry about late response, but issue still persists with 3.02:

![mmc_XwqF1ac1Oc](https://github.com/marticliment/WingetUI/assets/2620870/da6ab5c4-6a72-42b9-a41a-7aff329d31ca)


![image](https://github.com/marticliment/WingetUI/assets/2620870/b15ec4b4-787b-42db-914d-fcfeb6027929)

**Comment by marticliment** [comment] 2024-04-25 21:59
Which .NET do you have installed?

**Comment by fernandog** [comment] 2024-04-25 22:06
It's on the first screenshot. Here are the full details:

![image](https://github.com/marticliment/WingetUI/assets/2620870/4a3a5bbe-f7df-4bc6-9573-e470f4879cf0)

**Comment by marticliment** [comment] 2024-04-25 22:27
Please try uninstalling and installing .NEt 8.0.2

**Comment by fernandog** [comment] 2024-04-25 23:21
issue persists. Weird that in Event viewer it shows coreclr.dll, version: 8.0.324.11423

but in Winget folder, it has the coreclr.dll. Which explains why I had installed 8.0.4 and the first Event Viewer screenshot was showing 8.0.3

![image](https://github.com/marticliment/WingetUI/assets/2620870/9381be54-df3d-46e3-ba6d-56908d45df1d)


![image](https://github.com/marticliment/WingetUI/assets/2620870/4132a10b-8a5c-4d8d-8547-5634424e1aff)

**Comment by fernandog** [comment] 2024-04-25 23:40
Doesn't matter the version of .net desktop runtime I have installed. I loads the one from the Winget folder.

I replaced coreclr.dll inside Winget folder with 8.02, restarted and issue persisted. 

![image](https://github.com/marticliment/WingetUI/assets/2620870/9466d0af-7815-41fb-bd88-6ca434032bd7)


Then replaced coreclr.dll with 8.0.4, restarted and still no luck.

![image](https://github.com/marticliment/WingetUI/assets/2620870/c3f4b360-7943-4485-a964-8111e67ca025)

**Comment by fernandog** [comment] 2024-04-26 14:35
any idea what's going on? I can't understand this event viewer crash logs

**Comment by marticliment** [comment] 2024-04-26 14:55
There is something wrong with .NET. coreclr.dll is one of the main components of the .NET runtime, and it is crashing for some reason. I can't really do anything but test another version of NET and cross my fingers for it to work

**Comment by fernandog** [comment] 2024-04-26 15:40
What is weird is that it used to work with 8.0.2 and replacing the file inside Wigetui folder with the 8.02 doesn't work.

**Comment by Meche697** [comment] 2024-04-26 16:18
Any recent updates? MS is changing a lot of items with the upcoming 24H2 that they may be experimenting with the the feature updates...
Just a thought.

**Comment by marticliment** [comment] 2024-04-26 16:33
> What is weird is that it used to work with 8.0.2 and replacing the file inside Wigetui folder with the 8.02 doesn't work.

I don't think it is possble to _hot-swap_ a dll without recompiling a self-contained .NET app, so this might be the cause of the test you did failing

**Closed** 2024-05-19 12:56 UTC
Labels: bug, ready-to-go, important

**Comment by fernandog** [comment] 2024-05-19 18:41
tested new 3.1.0 alpha0, worked. thanks!
