### ISSUE TITLE
[ENHANCEMENT] Show installation path

### ISSUE THREAD

**Issue by SchreinerK** [marticliment/WingetUI#2015] opened 2024-03-21 14:34 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

The installation path of a package should be displayed.

### Describe how this new feature could help users.

After the installation you do not know where the package has been installed to because in many cases neither a start menu entry nor a desktop shortcut is created. displaying the path in the package information, being able to copy it and/or navigate to it would be helpful.

**Comment by marticliment** [comment] 2024-03-21 22:54
Duplicate of #1386

**Closed by marticliment** 2024-03-21 22:54 UTC
Labels: new-feature
