### ISSUE TITLE
Installed packages list will not populate unless I press the Search Mod drop-down menu (WingetUI 3.0.1)

### ISSUE THREAD

**Issue by zme-ul** [marticliment/WingetUI#1986] opened 2024-03-17 16:28 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

when I go into the Installed Packages, the list will not populate unless I press the Search Mod drop-down menu

before:
![Winget1](https://github.com/marticliment/WingetUI/assets/25272649/b5b5744f-32af-4cf7-81e4-dc8e1830adfc)

after:
![Winget2](https://github.com/marticliment/WingetUI/assets/25272649/a25db4a8-cae5-4457-942c-8756c28d9c2f)

### Steps to reproduce the issue

pretty self explanatory from the description and images attached

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.1
               Version Code 3.01
C:\Users\zmeul\AppData\Local\WingetUI\CachedLangFiles\lang_en.json
Loaded language locale: en
Api auth token: un5lojhs4ijxwo2ez4x6sr4uz1as7x7pqz4r3jk0pyg2edutnvvkbiqal8lrqp14
Starting update check
Api running on http://localhost:7058
Lang files were updated successfully
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
WingetUI is up to date
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: False
█ THE MANAGER IS DISABLED
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.2506                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.2506                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'B:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:23] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[17/03/2024 18:22:23] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:23] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\zmeul\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[17/03/2024 18:22:23] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:23] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[17/03/2024 18:22:23] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:24] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[17/03/2024 18:22:24] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:24] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[17/03/2024 18:22:24] Exit Code: -2147450735
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:24] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\zmeul\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[17/03/2024 18:22:24] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:25] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[17/03/2024 18:22:25] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:25] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
[17/03/2024 18:22:25] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:25] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
PS C:\Program Files\WingetUI> 
PS C:\Program Files\WingetUI>                 function Test-GalleryModuleUpdate {
>>                     param (
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Name,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [version] $Version,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Repository,
>>                         [switch] $NeedUpdateOnly
>>                     )
>>                     process {
>>                         $URLs = @{}
>>                         @(Get-PSRepository).ForEach({$URLs[$_.Name] = $_.SourceLocation})
>>                         $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                         [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                         $needsupdate = $Latest -gt $Version
>>                         if ($needsupdate) {
>>                                 Write-Output($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                         }
>>                     }
>>                 }
>>                 Get-InstalledModule | Test-GalleryModuleUpdate
PS C:\Program Files\WingetUI>                 exit
[17/03/2024 18:22:25] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:25] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  update --include-unknown  --accept-source-agreements
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.50 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.50 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.50 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.50 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.50 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.50 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.50 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.50 MB
  ████████████████████████████▒▒  9.00 MB / 9.50 MB
  ██████████████████████████████  9.50 MB / 9.50 MB
   - 
Name                                               Id                                Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Waterfox (x64 en-US)                               Waterfox.Waterfox                 < G5.0.2      G6.0.9        winget
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VCRedist.2015+.x64      14.38.33135.0 14.40.33617.1 winget
Microsoft ASP.NET Core 7.0.7 - Shared Framework (… Microsoft.DotNet.AspNetCore.7     7.0.7         7.0.17        winget
Microsoft Windows Desktop Runtime - 7.0.15 (x64)   Microsoft.DotNet.DesktopRuntime.7 7.0.15        7.0.17        winget
Microsoft ASP.NET Core 7.0.15 - Shared Framework … Microsoft.DotNet.AspNetCore.7     7.0.15        7.0.17        winget
Microsoft Windows Desktop Runtime - 7.0.7 (x64)    Microsoft.DotNet.DesktopRuntime.7 7.0.7         7.0.17        winget
6 upgrades available.
[17/03/2024 18:22:25] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [17/03/2024 18:22:25] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  list  --accept-source-agreements
   \ 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.50 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.50 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.50 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.50 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.50 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.50 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.50 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.50 MB
  ████████████████████████████▒▒  9.00 MB / 9.50 MB
  ██████████████████████████████  9.50 MB / 9.50 MB
   - 
Name                                          Id                                             Version           Source
-----------------------------------------------------------------------------------------------------------------------
Wartales                                      1272361289_is1                                 1.0.31946         
Wartales, Pirates of Belerion                 1932034254_is1                                 1.0.31946         
EarTrumpet                                    40459File-New-Project.EarTrumpet_1sdd7yawvg6ne 2.3.0.0           
WhatsApp                                      5319275A.WhatsAppDesktop_cv1g1gvanyjgm         2.2410.2.0        
Google Password Manager                       6e79b39f880b9e992c080f7f55c547a8               1.0               
7-Zip 23.01 (x64)                             7zip.7zip                                      23.01             winget
YouTube                                       890cfcaeb5d499dbeee17c7d16fdf7a9               1.0               
World_of_Warships                             909148281                                      Unknown           
MSI Center                                    9426MICRO-STARINTERNATION.MSICenter_kzh8wxbdk… 2.0.32.0          
AC3Filter 2.6.0b                              AC3Filter_is1                                  2.6.0b            
Sound Blaster AE-Series Driver                AESeries_is1                                   1.0.01.06         
AIMP                                          AIMP.AIMP                                      5.30.2533         winget
Creative ALchemy                              ALchemy                                        1.45              
Adobe Acrobat Reader                          AdobeAcrobatReaderCoreApp_pc75e8sa7ep4e        23.0.0.0          
MSI Afterburner 4.6.5                         Guru3D.Afterburner                             4.6.5             winget
Intel® Application Optimization               AppUp.IntelAPO-Applicationoverview_8j3eq9eme6… 9.0.11661.0       
Intel® Graphics Command Center                AppUp.IntelGraphicsExperience_8j3eq9eme6ctt    1.100.5390.0      
ThunderboltTM Control Center                  AppUp.ThunderboltControlCenter_8j3eq9eme6ctt   1.0.37.0          
Battle.net                                    Battle.net                                     Unknown           
CPUID CPU-Z 2.09                              CPUID.CPU-Z                                    2.09              winget
Dolby Digital Live Pack version 4.02.00       DDLMaster_is1                                  4.02.00           
DTS Connect Pack version 2.02.00              DTSMaster_is1                                  2.02.00           
Alienware Command Center                      DellInc.AlienwareCommandCenter_htrsf667h5kn2   5.6.1.0           
Diablo IV                                     Diablo IV                                      Unknown           
GlassWire 3.3 (remove only)                   GlassWire 3.3                                  3.3.664           
HWiNFO64                                      REALiX.HWiNFO                                  7.72              winget
Hard Disk Sentinel PRO                        XPDNXG5333CSVK                                 6.10              msstore
Host OpenAL                                   Host OpenAL                                    2.03              
K-Lite Codec Pack 18.2.0 Standard             KLiteCodecPack_is1                             18.2.0            
KeePass Password Safe 2.56                    DominikReichl.KeePass                          2.56              winget
Cinebench                                     MAXONComputerGmbH.Cinebench_rsne5bsk8s7tj      23.2.0.0          
Microsoft Edge                                Microsoft.Edge                                 122.0.2365.92     winget
Microsoft Edge Update                         Microsoft Edge Update                          1.3.185.21        
Microsoft Edge WebView2 Runtime               Microsoft.EdgeWebView2Runtime                  122.0.2365.80     winget
Web Search from Microsoft Bing                Microsoft.BingSearch_8wekyb3d8bbwe             1.0.91.0          
MSN Weather                                   Microsoft.BingWeather_8wekyb3d8bbwe            4.53.52331.0      
App Installer                                 Microsoft.AppInstaller                         1.22.10661.0      winget
HEIF Image Extensions                         Microsoft.HEIFImageExtension_8wekyb3d8bbwe     1.0.63001.0       
HEVC Video Extensions from Device Manufactur… Microsoft.HEVCVideoExtension_8wekyb3d8bbwe     2.1.451.0         
Microsoft Edge                                Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe   122.0.2365.92     
Microsoft .Net Native Framework Package 2.1   Microsoft.NET.Native.Framework.2.1_8wekyb3d8b… 2.1.27427.0       
Microsoft .Net Native Framework Package 2.2   Microsoft.NET.Native.Framework.2.2_8wekyb3d8b… 2.2.29512.0       
Microsoft .Net Native Runtime Package 2.1     Microsoft.NET.Native.Runtime.2.1_8wekyb3d8bbwe 2.1.26424.0       
Microsoft .Net Native Runtime Package 2.2     Microsoft.NET.Native.Runtime.2.2_8wekyb3d8bbwe 2.2.28604.0       
Raw Image Extension                           Microsoft.RawImageExtension_8wekyb3d8bbwe      2.3.611.0         
Snipping Tool                                 Microsoft.ScreenSketch_8wekyb3d8bbwe           11.2312.33.0      
Windows Security                              Microsoft.SecHealthUI_8wekyb3d8bbwe            1000.25992.9000.0 
Microsoft Engagement Framework                Microsoft.Services.Store.Engagement_8wekyb3d8… 10.0.23012.0      
Store Experience Host                         Microsoft.StorePurchaseApp_8wekyb3d8bbwe       22312.1401.4.0    
Microsoft.UI.Xaml.2.7                         Microsoft.UI.Xaml.2.7                          7.2208.15002.0    winget
Microsoft.UI.Xaml.2.8                         Microsoft.UI.Xaml.2.8                          8.2310.30001.0    winget
Microsoft Visual C++ 2015 UWP Desktop Runtim… Microsoft.VCLibs.Desktop.14                    14.0.33519.0      winget
Microsoft Visual C++ 2015 UWP Runtime Package Microsoft.VCLibs.140.00_8wekyb3d8bbwe          14.0.33519.0      
VP9 Video Extensions                          Microsoft.VP9VideoExtensions_8wekyb3d8bbwe     1.1.451.0         
Web Media Extensions                          Microsoft.WebMediaExtensions_8wekyb3d8bbwe     1.0.62931.0       
Webp Image Extensions                         Microsoft.WebpImageExtension_8wekyb3d8bbwe     1.1.522.0         
Windows App Runtime DDLM 5001.70.1338.0-x6    Microsoft.WinAppRuntime.DDLM.5001.70.1338.0-x… 5001.70.1338.0    
Windows App Runtime DDLM 5001.70.1338.0-x8    Microsoft.WinAppRuntime.DDLM.5001.70.1338.0-x… 5001.70.1338.0    
Microsoft Photos                              Microsoft.Windows.Photos_8wekyb3d8bbwe         2024.11020.28003… 
Windows Clock                                 Microsoft.WindowsAlarms_8wekyb3d8bbwe          1.0.189.0         
WindowsAppRuntime.1.3                         Microsoft.WindowsAppRuntime.1.3_8wekyb3d8bbwe  3000.934.1904.0   
WindowsAppRuntime.1.4                         Microsoft.WindowsAppRuntime.1.4_8wekyb3d8bbwe  4000.1049.117.0   
WindowsAppRuntime.1.5                         Microsoft.WindowsAppRuntime.1.5_8wekyb3d8bbwe  5001.70.1338.0    
Windows Calculator                            Microsoft.WindowsCalculator_8wekyb3d8bbwe      11.2401.0.0       
Windows Sound Recorder                        Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe   1.0.76.0          
Microsoft Store                               Microsoft.WindowsStore_8wekyb3d8bbwe           22401.1401.7.0    
Windows Terminal                              Microsoft.WindowsTerminal                      1.19.10573.0      winget
Windows Package Manager Source (winget)       Microsoft.Winget.Source_8wekyb3d8bbwe          2023.1213.1518.72 
Game Bar                                      Microsoft.XboxGamingOverlay_8wekyb3d8bbwe      7.124.2141.0      
WinAppRuntime.Main.1.5                        MicrosoftCorporationII.WinAppRuntime.Main.1.5… 5001.70.1338.0    
WinAppRuntime.Singleton                       MicrosoftCorporationII.WinAppRuntime.Singleto… 5001.70.1338.0    
Windows Web Experience Pack                   MicrosoftWindows.Client.WebExperience_cw5n1h2… 424.1301.270.0    
Cross Device Experience Host                  MicrosoftWindows.CrossDevice_cw5n1h2txyewy     0.24022.86.0      
NVIDIA Control Panel                          NVIDIACorp.NVIDIAControlPanel_56jybvy8sckqj    8.1.964.0         
Notepad++ (64-bit x64)                        Notepad++.Notepad++                            8.6.4             winget
Notepad++                                     NotepadPlusPlus_7njy0v32s6xk6                  1.0.0.0           
RivaTuner Statistics Server 7.3.5             RTSS                                           7.3.5             
Sound Blaster Command version 3.5.10.00       CreativeTechnology.SoundBlasterCommand         3.5.10.00         winget
Steam                                         Valve.Steam                                    2.10.91.91        winget
Last Epoch                                    Steam App 899770                               Unknown           
Stremio                                       Stremio.Stremio                                4.4.165           winget
Vivaldi                                       Vivaldi                                        6.6.3271.50       
Wargaming.net Game Center                     Wargaming.GameCenter                           24.0.0.5034       winget
Waterfox (x64 en-US)                          Waterfox.Waterfox                              < G5.0.2          winget
Outlook (PWA)                                 b5a8522579266029498f0305cc40d47b               1.0               
Docs                                          e239cac31e72e1146249eb449cd1453b               1.0               
Microsoft Visual C++ 2013 Redistributable (x… Microsoft.VCRedist.2013.x64                    12.0.40664.0      winget
Windows 11 Installation Assistant             Microsoft.WindowsInstallationAssistant         1.4.19041.3630    winget
MSI Center SDK                                {15289038-41BE-48F8-B8B9-0B1021D3089E}}_is1    3.2024.0202.01    
Microsoft Visual C++ 2010  x64 Redistributab… Microsoft.VCRedist.2010.x64                    10.0.40219        winget
LibreOffice 24.2.1.2                          TheDocumentFoundation.LibreOffice              24.2.1.2          winget
Samsung Magician                              Samsung.SamsungMagician                        8.0.1.1000        winget
Microsoft Visual C++ 2012 Redistributable (x… Microsoft.VCRedist.2012.x86                    11.0.61030.0      winget
Microsoft Visual C++ 2015-2022 Redistributab… Microsoft.VCRedist.2015+.x64                   14.38.33135.0     winget
Microsoft ASP.NET Core 7.0.7 - Shared Framew… Microsoft.DotNet.AspNetCore.7                  7.0.7             winget
Kingston SSD Manager x64 1.5.3.6              Kingston.SSDManager                            1.5.3.6           winget
Microsoft Visual C++ 2015-2022 Redistributab… Microsoft.VCRedist.2015+.x64                   14.40.33617.1     winget
Epic Online Services                          {57A956AB-4BCC-45C6-9B40-957E4E125568}         2.0.44.0          
Microsoft Visual C++ 2008 Redistributable - … Microsoft.VCRedist.2008.x64                    9.0.30729.6161    winget
Revo Uninstaller Pro 5.2.2                    RevoUninstaller.RevoUninstallerPro             5.2.2             winget
Microsoft Windows Desktop Runtime - 7.0.15 (… Microsoft.DotNet.DesktopRuntime.7              7.0.15            winget
Microsoft Visual C++ 2005 Redistributable     Microsoft.VCRedist.2005.x86                    8.0.61001         winget
PrimoCache 4.3.0                              {7A37EA43-BF6F-4DB7-83DB-97AA19BF9408}_is1     4.3.0             
Google Chrome                                 Google.Chrome                                  122.0.6261.129    winget
WingetUI                                      {889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1     3.0.1             
TechPowerUp GPU-Z                             TechPowerUp.GPU-Z                              2.57.0            winget
Microsoft Visual C++ 2008 Redistributable - … Microsoft.VCRedist.2008.x86                    9.0.30729.6161    winget
Microsoft Visual C++ 2013 Redistributable (x… Microsoft.VCRedist.2013.x86                    12.0.40664.0      winget
paint.net                                     dotPDN.PaintDotNet                             5.0.13            winget
Adobe Acrobat (64-bit)                        {AC76BA86-1033-1033-7760-BC15014EA700}         24.001.20604      
NVIDIA Graphics Driver 551.76                 {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_Displa… 551.76            
NVIDIA FrameView SDK 1.4.9615.33661400        {B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_FrameV… 1.4.9615.33661400 
Epic Games Launcher                           EpicGames.EpicGamesLauncher                    1.3.93.0          winget
Microsoft Update Health Tools                 {C6FD611E-7EFE-488C-A0E0-974C09EF6473}         5.72.0.0          
ExplorerPatcher                               valinet.ExplorerPatcher                        22621.3296.64.1   winget
Alienware Command Center Package Manager      {D2DA930B-CB5D-4DD6-BF62-BE6C310A353D}         5.6.1.0           
Futuremark SystemInfo                         {DB3FC272-D04E-42E1-A981-20A781A9561C}         5.69.1204.0       
Microsoft Visual C++ 2010  x86 Redistributab… Microsoft.VCRedist.2010.x86                    10.0.40219        winget
Microsoft Visual C++ 2005 Redistributable (x… {ad8a2fa1-06e7-4b0d-927d-6e54b3d31028}         8.0.61000         
Microsoft ASP.NET Core 7.0.15 - Shared Frame… Microsoft.DotNet.AspNetCore.7                  7.0.15            winget
Microsoft Visual C++ 2012 Redistributable (x… Microsoft.VCRedist.2012.x64                    11.0.61030.0      winget
Microsoft Windows Desktop Runtime - 7.0.7 (x… Microsoft.DotNet.DesktopRuntime.7              7.0.7             winget
Intel(R) Chipset Device Software              {f48aa9ec-42b9-428a-8536-42b3a4b738c8}         10.1.19627.8423   
Microsoft Windows Desktop Runtime - 8.0.3 (x… Microsoft.DotNet.DesktopRuntime.7              > 7.0.17          winget
[17/03/2024 18:22:25] Exit Code: 0
```

**Comment by marticliment** [comment] 2024-03-17 17:42
Duplicate of #1844

**Closed by marticliment** 2024-03-17 17:42 UTC
Labels: bug
