### ISSUE TITLE
Sort tables by version numbering 

### ISSUE THREAD

**Issue by ladiko** [marticliment/WingetUI#1005] opened 2023-05-05 02:50 UTC
I would enjoy to properly sort searches for example "JRE" or "JDK" by version number as those are offered in trillions of versions by many companys like Oracle, Microsoft, IBM, Amazon, Eclipse, RedHat, IBM, Apple, OpenJDK, did I mention IBM? you name it, they have it... https://whichjdk.com

I am pretty sure python has a simple pre-defined way (table column header parameter or so) to sort a single column by version number. That would be helpful, because right now the sorting is alphabetically. Thanks for this great application and enjoy your Ko-fi. 

Ohh and nice dream setup on your website!

```
1.0.0.0
1.12.0.0
1.2.0.0
1.8.0.0
10.0.0.1
11.0.0.0
11.198.0.0
11.25.0.0
17.198.0.0
17.2.0.0
2.0.0.0
20.0.0.0
8.1.0.0
9.0.0.0
```

<img src="https://user-images.githubusercontent.com/1856019/236366643-04d21769-a179-40ce-b152-89e336ef4705.png" width="50%" height="50%">

**Comment by ppvnf** [comment] 2023-05-05 06:10
related to https://github.com/marticliment/WingetUI/issues/844

**Comment by marticliment** [comment] 2023-05-05 13:03
Yes, it is a duplicate of #844

**Closed** 2023-05-05 13:04 UTC
Labels: duplicate
