### ISSUE TITLE
[FEATURE REQUEST] check for updates every 24h or once a week

### ISSUE THREAD

**Issue by reaseno** [marticliment/WingetUI#716] opened 2023-02-15 12:38 UTC
## Before submitting the issue
- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**

Some of my installed packages seem to get an update twice a day, which annoys me with the update notifications. So it would help me if I could set update checks to 24h or once a week.

**Comment by marticliment** [comment] 2023-02-15 13:59
duplicate of #647

**Closed by marticliment** 2023-02-15 13:59 UTC
Labels: feature-request

**Comment by reaseno** [comment] 2023-02-15 14:48
I have not found this. Sorry 🙈
