### ISSUE TITLE
[BUG] Cannot search for "jj" a.k.a. jujutsu version control

### ISSUE THREAD

**Issue by realmazharhussain** [marticliment/WingetUI#2186] opened 2024-05-02 07:05 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Cannot search for [jj](https://martinvonz.github.io/jj) because it has less than 3 characters in its name. Also, cannot search using the word jujutsu because that returns an empty result.

I can search via both `jj` and `jujutsu` search terms using `winget find -q <search-term>` command.

### Steps to reproduce the issue

1. Open Winget UI.
2. Make sure you're in Discover Packages tab.
3. Do one of below
   1. Type `jj` in the search field on the top right.
   2. Type `jujutsu` in the search field

### WingetUI Log

```text
Not needed. UX issue.
```

### Package Managers Logs

```text
Not needed. UX issue.
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/67191572/056619bd-3738-45f4-a5fd-f9b6be8a742e)
![image](https://github.com/marticliment/WingetUI/assets/67191572/bf7cb95f-a34e-4b42-8056-33dd0117b6fb)
![image](https://github.com/marticliment/WingetUI/assets/67191572/ae98d62b-4fd8-4c65-8230-8cfffef876f5)

**Comment by marticliment** [comment] 2024-05-02 13:48
Hello,

This is the same issue as #2181, so I am going to close it and mark it as a duplicate


duplicate of #2181

**Closed by marticliment** 2024-05-02 13:48 UTC
Labels: bug

**Comment by realmazharhussain** [comment] 2024-05-02 14:41
There is one aspect of this issue that #2181 is missing

Running `winget find -q jujutsu` prints

```
Name Id            Version Match            Source
--------------------------------------------------
jj   martinvonz.jj 0.16.0  Moniker: Jujutsu winget
```

While searching for "jujutsu" in WingetUI yeilds no results.
