### ISSUE TITLE
[FEATURE REQUEST] Create packages

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#1380] opened 2023-09-19 22:56 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Add support for creating package manifests like Komac.

### Describe how this new feature could help users.

It will make us easily submit packages and finally have a GUI manifest creator!

**Comment by ppvnf** [comment] 2023-09-20 05:12
similar to https://github.com/marticliment/WingetUI/issues/948

**Comment by marticliment** [comment] 2023-09-20 11:48
duplicate of #948

**Closed by marticliment** 2023-09-20 11:48 UTC
Labels: new-feature
