### ISSUE TITLE
[ENHANCEMENT] (Incorporate a progress bar or a visual indicator that shows the status of the installation, update or uninstallation of the packages.)

### ISSUE THREAD

**Issue by andresgarcia0313** [marticliment/WingetUI#1309] opened 2023-08-26 23:17 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Hello, I am a user of WingetUI and I would like to request a new improvement that I think could improve the information and control of the operations with the packages. It is about incorporating a progress bar or a visual indicator that shows the status of the installation, update or uninstallation of the packages.

The idea is that the application can display a progress bar or a visual indicator that indicates the percentage, time or size of the operation that is being performed with a package. The user could see the progress and result of the operation, as well as cancel it or pause it if they wish.

The improvement could be implemented by adding a progress bar or a visual indicator in the interface, next to the name or icon of the package. The user could interact with the bar or indicator to get more information or to perform actions on the operation.

### Describe how this improvement could help users.

I think this improvement could help users in several ways:

It would allow them to know and monitor the status and result of the operations with the packages, avoiding possible confusion, errors or interruptions.
It would facilitate the handling and management of the operations with the packages, allowing them to cancel them or pause them if they change their mind or have any problem.
It would offer them a more transparent and smooth experience with the application, as they could see and control the operations with the packages from the same interface.
I hope you like this idea and give me your feedback on it. Thank you for your attention and for your excellent work with WingetUI. 😊

**Comment by marticliment** [comment] 2023-08-27 20:04
duplicate of #1164

**Closed by marticliment** 2023-08-27 20:04 UTC
Labels: enhancement
