### ISSUE TITLE
Status bar stuck on Cancel

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1541] opened 2023-11-01 02:35 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Just installed one single update, for Powertoys. I noticed that I had accidentally selected more updates so I pressed "Cancel". It had already installed one other update (Zoom)but so far so good.

I then clicked the icon(with no mouseover :)  to refresh the available updates again, made sure that I had only selected "PowerToys" and let WGUI install it. After it finished the status bar says "Successfully installed" but it shows the "Cancel" button instead of the "OK" button. See the attached screenshot.
![image](https://github.com/marticliment/WingetUI/assets/24390228/5148355a-6087-4be4-bd74-5bef0b1738e0)

### WingetUI Log

```text
NA
```

### Package Managers Logs

```text
NA
```

**Comment by marticliment** [comment] 2023-11-01 13:14
Duplicate of #1491

**Closed** 2023-11-01 13:14 UTC
Labels: bug, duplicate
