### ISSUE TITLE
[ENHANCEMENT] Localization for Kannada Language

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2359] opened 2024-06-29 05:39 UTC
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Support Kannada language.

### Describe how this improvement could help users

This could help avoid errors like: #2358

**Comment by marticliment** [comment] 2024-06-29 15:28
The UI Should support special characters. I am afraid #2358 is a duplicate of #2242

**Closed by marticliment** 2024-06-29 15:28 UTC
Labels: enhancement

**Comment by skanda890** [comment] 2024-06-29 16:14
> The UI Should support special characters. I am afraid #2358 is a duplicate of #2242

#2242 says about Chinese #2358 says about Kannada.

**Comment by marticliment** [comment] 2024-06-29 16:38
Yes, but the root of the issue is the same

**Comment by marticliment** [comment] 2024-07-01 12:51
If you want to add Kannada language, please read https://github.com/marticliment/WingetUI/wiki#translating-wingetui
