### ISSUE TITLE
Mouseover for the icones on the main page

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1538] opened 2023-10-31 12:28 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

It's not evident what each of the icons on the main screen does. Please consider implementing "Mouseover" the standard way, eg show "mouseover" help text if the cursor is hoovering over an icon for say 1 second or so.hovering

### Describe how this improvement could help users.

General understanding of what each button/function does.

**Comment by marticliment** [comment] 2023-10-31 14:58
duplicate of #1410

**Closed by marticliment** 2023-10-31 14:58 UTC
Labels: enhancement

**Comment by chjohans** [comment] 2023-10-31 16:26
Too bad, I was quite confused re those icons when I first started WingetUI. I would have thought that you could have added the few lines of code that this requires. :)
