### ISSUE TITLE
[BUG] Theme breaks when changing Windows Accent Colour

### ISSUE THREAD

**Issue by FlamingPhoenix40** [marticliment/WingetUI#1407] opened 2023-09-25 20:01 UTC
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I use the Dark theme for WingetUI. Whenever Windows' accent colour changes, the theming of WingetUI breaks and goes white, but it is not actually switching to the light theme. Text becomes unreadable as well. Only way to fix it is to go to settings, switch to light mode and then back to dark mode. I'll attach a screenshot of the program in the broken state, as well as a video of it happening in the Screenshots and videos part of this template.

### Steps to reproduce the issue

Go to Windows Settings app --> Personalization --> Colours
Change the "Accent colour" to anything other than the currently set colour.
After a few seconds, WingetUI theming breaks and goes white/light.

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.003999471664428711 to load all language files
🟢 checkQueue Thread started!
🟡 System chocolatey used
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🔵 Loading WingetUI AUMID...
🔵 Starting update check
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1695659653.442675]
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
{'sudoFound': True, 'sudoVersion': '', 'WingetFound': False, 'WingetVersion': 'Winget is disabled', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': True, '.NET ToolVersion': '7.0.203\r', 'ChocolateyFound': True, 'ChocolateyVersion': '2.2.2  '}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/installed_masked_white.png
🟢 Discover tab loaded successfully
🟢 Total packages: 0
Can't disconnect
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/update_masked_white.png
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
Can't disconnect
Can't disconnect
Can't disconnect
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Uninstall tab loaded successfully
🔵 Starting Chocolatey search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated
Can't disconnect
Can't disconnect
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟢 Settings tab loaded!
🔵 Reloading Scoop sources...
🟢 About tab loaded!
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Main application loaded...
🟢 Searching for string ""
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
🟢 Chocolatey search for installed packages finished with 33 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 34
🔵 Starting .NET Tool search for updates
🔵 Starting Chocolatey search for updates
🟢 .NET Tool search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 9 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 9
🔵 Starting Chocolatey search for installed packages
🔵 Starting .NET Tool search for installed packages
🟢 Searching for string ""
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting .NET Tool search for installed packages
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated
🟢 .NET Tool search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 33 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 34
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
C:/Program Files/WingetUI/resources/installed_masked_black.png
C:/Program Files/WingetUI/resources/update_masked_black.png
C:/Program Files/WingetUI/resources/pin_masked_black.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
C:/Program Files/WingetUI/resources/installed_masked_black.png
C:/Program Files/WingetUI/resources/update_masked_black.png
C:/Program Files/WingetUI/resources/pin_masked_black.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
C:/Program Files/WingetUI/resources/installed_masked_black.png
C:/Program Files/WingetUI/resources/update_masked_black.png
C:/Program Files/WingetUI/resources/pin_masked_black.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
C:/Program Files/WingetUI/resources/installed_masked_black.png
C:/Program Files/WingetUI/resources/update_masked_black.png
C:/Program Files/WingetUI/resources/pin_masked_black.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
C:/Program Files/WingetUI/resources/installed_masked_black.png
C:/Program Files/WingetUI/resources/update_masked_black.png
C:/Program Files/WingetUI/resources/pin_masked_black.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
C:/Program Files/WingetUI/resources/installed_masked_black.png
C:/Program Files/WingetUI/resources/update_masked_black.png
C:/Program Files/WingetUI/resources/pin_masked_black.png
C:/Program Files/WingetUI/resources/installed_masked_white.png
C:/Program Files/WingetUI/resources/update_masked_white.png
C:/Program Files/WingetUI/resources/pin_masked_white.png
🔵 Loading WingetUI log...
🔵 Saving log...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 -------dotnet
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated

-------dotnet
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated

---------Chocolatey
Chocolatey v2.2.2
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\choco.exe.old' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\choco.exe.old' is denied.
Maximum tries of 3 reached. Throwing error.
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-fastanswers.extension 0.0.2.2
chocolateygui 2.1.0
chocolatey-os-dependency.extension 0.0.1
chocolatey-windowsupdate.extension 1.0.5
dotnetfx 4.8.0.20220524
flow-launcher 1.16.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
localsend 1.10.0
localsend.portable 1.10.0
mpc-be 1.6.8.5
mpvio 0.36.0
mpvio.install 0.36.0
netfx-4.8 4.8.0.20220524
nirlauncher 1.30.3
notepadplusplus 8.5.4
notepadplusplus.install 8.5.4
streamlink 6.0.1.1
streamlink-twitch-gui 2.4.1
sysinternals 2023.7.26
thunderbird 115.1.0
vcredist140 14.36.32532
winrar 6.23.0
30 packages installed.
--------dotnet
---------Chocolatey
Chocolatey v2.2.2
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\choco.exe.old' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\choco.exe.old' is denied.
Maximum tries of 3 reached. Throwing error.
Outdated Packages
Output is package name | current version | available version | pinned?

flow-launcher|1.16.0|1.16.1|false
localsend|1.10.0|1.11.1|false
localsend.portable|1.10.0|1.11.1|false
mpc-be|1.6.8.5|1.6.9|false
nirlauncher|1.30.3|1.30.5|false
notepadplusplus|8.5.4|8.5.7|false
notepadplusplus.install|8.5.4|8.5.7|false
streamlink|6.0.1.1|6.2.0.1|false
thunderbird|115.1.0|115.2.3|false

Chocolatey has determined 9 package(s) are outdated.-------dotnet
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated

-------dotnet
Package Id                 Version      Commands
-------------------------------------------------------------
dotnet-tools-outdated      0.6.0        dotnet-tools-outdated

---------Chocolatey
Chocolatey v2.2.2
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\choco.exe.old' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\choco.exe.old' is denied.
Maximum tries of 3 reached. Throwing error.
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolatey-fastanswers.extension 0.0.2.2
chocolateygui 2.1.0
chocolatey-os-dependency.extension 0.0.1
chocolatey-windowsupdate.extension 1.0.5
dotnetfx 4.8.0.20220524
flow-launcher 1.16.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
localsend 1.10.0
localsend.portable 1.10.0
mpc-be 1.6.8.5
mpvio 0.36.0
mpvio.install 0.36.0
netfx-4.8 4.8.0.20220524
nirlauncher 1.30.3
notepadplusplus 8.5.4
notepadplusplus.install 8.5.4
streamlink 6.0.1.1
streamlink-twitch-gui 2.4.1
sysinternals 2023.7.26
thunderbird 115.1.0
vcredist140 14.36.32532
winrar 6.23.0
30 packages installed.
```

### Relevant information

I noticed it happening because on Windows, I'm using a wallpaper slideshow, with "Automatic accent colour" enabled. It does however also happen on a manual accent colour change while the wallpaper doesn't change.

### Screenshots and videos

https://github.com/marticliment/WingetUI/assets/144808356/b6215187-069b-4857-95c0-f8fa7f86dfd5

![Screenshot_35_2023-09-25_WingetUI](https://github.com/marticliment/WingetUI/assets/144808356/cc3dce2d-8ff1-47a7-a1de-bc99d28f57c9)

**Comment by marticliment** [comment] 2023-09-26 20:17
Possible same cause as #1411

**Comment by isuru221** [comment] 2023-09-27 17:44
this happens on my pc too

**Comment by Masamune3210** [comment] 2023-09-28 19:31
same thing happens to me, was just actually looking for an existing issue to see if i needed to report it or not myself

**Comment by djwinston** [comment] 2023-10-03 19:56
The same thing is happening to me. I noticed it ~ two weeks ago. The colour accent is auto, but the bug appears not when changing the colour. The bug occurs after the computer wakes up from sleep mode. The temporary solution is to always switch the application theme.

**Comment by ryder1977** [comment] 2023-10-20 17:30
Same here.

**Comment by jarod186** [comment] 2023-10-23 08:12
same problem here

**Comment by jessehouwing** [comment] 2023-10-30 19:51
Same happens when switching from light to dark mode. I'm running AutoDarkMode and every evening wingetUI looks terrible.

**Comment by nemchik** [comment] 2023-11-09 14:07
I'm experiencing this as well, but in my case I have my `Accent color` set to `Automatic`, and it changed anytime my background changes, which happens daily because I use the `Windows spotlight` background. I wasn't sure what the cause was with WingetUI until coming here to search, but I can now confirm I see the same behavior as the video in the top post when testing changing the `Accent color`. So just to add, it also happens when `Automatic` changes the `Accent color`.

**Comment by lokejonatan** [comment] 2023-11-16 08:49
> I'm experiencing this as well, but in my case I have my `Accent color` set to `Automatic`, and it changed anytime my background changes, which happens daily because I use the `Windows spotlight` background. I wasn't sure what the cause was with WingetUI until coming here to search, but I can now confirm I see the same behavior as the video in the top post when testing changing the `Accent color`. So just to add, it also happens when `Automatic` changes the `Accent color`.
> 
> edit: I also tried deleting `~/.wingetui` and restarting the application and can still confirm the issue exists.

I have almost the same setup as you, and am experiencing the same. 😣

**Comment by raghavdhingra24** [comment] 2023-11-18 07:39
A workaround was made in PR #1524, most probably it will get shipped in next release.

**Comment by marticliment** [comment] 2023-11-18 07:49
yes, this issue was fixed by that PR

**Closed by marticliment** 2023-11-18 07:49 UTC
Labels: bug, ready-to-go, appearance

**Comment by sunnyd24** [comment] 2024-03-27 12:08
This issue seems to have returned file version 1.9.7.30920 or product version 2.20.

![image](https://github.com/marticliment/WingetUI/assets/46629122/92f0c13f-112b-4720-bd43-438081afa4f2)

**Comment by marticliment** [comment] 2024-03-27 12:13
Please install WingetUI 3.0.1
