### ISSUE TITLE
[FEATURE REQUEST] (希望能添加一个自定义代理的功能)

### ISSUE THREAD

**Issue by irx999** [marticliment/WingetUI#1232] opened 2023-07-22 02:58 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Hello, due to Chinese mainland network limitations A lot of software is software on github Need proxy to download, hope to add a custom proxy function to the software, otherwise I need to open the global proxy to download, I hope you can add this function, it is very helpful for our Chinese users, thank you！

### Describe how this new feature could help users.

Hello, due to Chinese mainland network limitations A lot of software is software on github Need proxy to download, hope to add a custom proxy function to the software, otherwise I need to open the global proxy to download, I hope you can add this function, it is very helpful for our Chinese users, thank you！

**Comment by ppvnf** [comment] 2023-07-23 06:41
this is similar to https://github.com/marticliment/WingetUI/issues/1016

**Comment by marticliment** [comment] 2023-07-29 18:02
This is a duplicate of #1016

**Closed** 2023-07-29 18:02 UTC
Labels: new-feature, duplicate
