### ISSUE TITLE
[BUG] (CLI generates random text strings "â–ˆâ–ˆâ–" to command output)

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [marticliment/WingetUI#1935] opened 2024-03-14 04:59 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

As the title suggests, the interface installation progress text window and the terminal output logs are generating (printing) the string "â–ˆâ–ˆâ–". **Apparently it's just a visual bug, here it was also thrown as a CLI log after the .NET SDK update failed** 
[See Attached Screenshots and txt Log]

### Steps to reproduce the issue

Using WingetUI 3.00 after restart (system and program) Run a normal update.
Score Bar will show Random Characters and save in the tasks logs

### WingetUI Log

```text
-Log Too Long (Exceed maximum 65536 characters). -Attached As TXT File
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:31] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[2024-03-13 22:06:31] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:32] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[2024-03-13 22:06:32] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:33] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\charl\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[2024-03-13 22:06:33] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:36] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[2024-03-13 22:06:36] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:36] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\charl\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[2024-03-13 22:06:36] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:37] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\charl\.dotnet\tools\dotnet-tools-outdated.exe
█  Arguments: 
[2024-03-13 22:06:37] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:37] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
Package Id                 Version      Commands             
-------------------------------------------------------------
dotnet-tools-outdated      0.7.1        dotnet-tools-outdated
[2024-03-13 22:06:37] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:37] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\charl\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  list
Chocolatey v2.2.2
mediainfo 24.1.1
mp3tag 3.24.0
zoom-client 4.6.20033.407
3 packages installed.
[2024-03-13 22:06:37] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:37] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\Python312\python.exe
█  Arguments:  -m pip list
Package Version
------- -------
pip     24.0
[2024-03-13 22:06:37] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:37] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[2024-03-13 22:06:37] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:38] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\charl\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  outdated
Chocolatey v2.2.2
Outdated Packages
 Output is package name | current version | available version | pinned?
Chocolatey has determined 0 package(s) are outdated. 
[2024-03-13 22:06:38] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:38] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\Python312\python.exe
█  Arguments:  -m pip list --outdated
[2024-03-13 22:06:38] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:38] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
PS C:\Program Files\WingetUI> 
PS C:\Program Files\WingetUI>                 function Test-GalleryModuleUpdate {
>>                     param (
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Name,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [version] $Version,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Repository,
>>                         [switch] $NeedUpdateOnly
>>                     )
>>                     process {
>>                         $URLs = @{}
>>                         @(Get-PSRepository).ForEach({$URLs[$_.Name] = $_.SourceLocation})
>>                         $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                         [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                         $needsupdate = $Latest -gt $Version
>>                         if ($needsupdate) {
>>                                 Write-Output($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                         }
>>                     }
>>                 }
>>                 Get-InstalledModule | Test-GalleryModuleUpdate
>>                 exit
>>                 
[2024-03-13 22:06:38] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:39] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: -NoProfile -Command Get-InstalledModule
[2024-03-13 22:06:39] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:40] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  update --include-unknown  --accept-source-agreements
   \ 
   / 
   \ 
   / 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.49 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.49 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.49 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.49 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.49 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.49 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.49 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.49 MB
  ████████████████████████████▒▒  9.00 MB / 9.49 MB
  ██████████████████████████████  9.49 MB / 9.49 MB
   - 
   | 
   - 
Name                                                Id                             Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------
MediaInfo 24.01                                     MediaArea.MediaInfo.GUI        24.01          24.01.1        winget
App Installer                                       Microsoft.AppInstaller         1.22.10582.0   1.22.10661.0   winget
OBS Studio                                          OBSProject.OBSStudio           Unknown        30.1.0         winget
Blender                                             BlenderFoundation.Blender      Unknown        4.0.2          winget
WinRAR 6.24 (64-bit)                                RARLab.WinRAR                  6.24.0         7.00.0         winget
Microsoft Visual C++ 2015-2022 Redistributable (x6… Microsoft.VCRedist.2015+.x86   14.38.33130.0  14.38.33135.0  winget
Microsoft Visual C++ 2015-2022 Redistributable (x8… Microsoft.VCRedist.2015+.x86   14.38.33130.0  14.38.33135.0  winget
Malwarebytes version 4.6.8.311                      Malwarebytes.Malwarebytes      4.6.8.311      4.6.10.316     winget
Microsoft .NET SDK 8.0.103 (x64)                    Microsoft.DotNet.SDK.8         8.0.103        8.0.202        winget
GPT4All                                             nomic.gpt4all                  2.6.1          2.7.0          winget
Google Chrome                                       Google.Chrome                  122.0.6261.113 122.0.6261.129 winget
Eclipse Temurin JDK con Hotspot 21.0.1+12 (x64)     EclipseAdoptium.Temurin.21.JDK 21.0.1.12      21.0.2.13      winget
Eclipse Temurin JRE con Hotspot 21.0.1+12 (x64)     EclipseAdoptium.Temurin.21.JRE 21.0.1.12      21.0.2.13      winget
OpenToonz version 1.7.1                             DWANGO.OpenToonz.Nightly       1.7.1          2023.10.31     winget
Microsoft Visual Studio Code                        Microsoft.VisualStudioCode     1.87.1         1.87.2         winget
16 upgrades available.
The following packages have an upgrade available, but require explicit targeting for upgrade:
Name    Id              Version  Available Source
-------------------------------------------------
Discord Discord.Discord 1.0.9032 1.0.9035  winget
1 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.
[2024-03-13 22:06:40] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [2024-03-13 22:06:41] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  list  --accept-source-agreements
   \ 
   / 
   \ 
   / 
   \ 
   / 
  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.49 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.49 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.49 MB
  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.49 MB
  ███████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.49 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.49 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.49 MB
  █████████████████████████▒▒▒▒▒  8.00 MB / 9.49 MB
  ████████████████████████████▒▒  9.00 MB / 9.49 MB
  ██████████████████████████████  9.49 MB / 9.49 MB
   - 
   | 
[2024-03-13 22:06:41] Exit Code: 0
```

### Relevant information

My system is Windows 11 with English as the base language (default) and system, reading and writing and Spanish as a secondary language (Never used in the system and second). WingetUI language is set to System Default _(But it shows mixed sentences between Spanish and English in some places)_

### Screenshots and videos

![Screenshot (1804)](https://github.com/marticliment/WingetUI/assets/64709446/c9a8614c-fee0-4397-86e5-7daae843d63f)
![Screenshot (1803)](https://github.com/marticliment/WingetUI/assets/64709446/201a80b3-dc45-4a46-bb46-7bea3f6f7c91)
[WingetUITASKS LOGS 2024-03-13T2256CST.txt](https://github.com/marticliment/WingetUI/files/14596828/WingetUITASKS.LOGS.2024-03-13T2256CST.txt)

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment] 2024-03-14 05:16
Languages installed in Windows 11 (Although the language mix does not bother me personally, this could be the cause or be related to the failure)
![image](https://github.com/marticliment/WingetUI/assets/64709446/d9b34250-5155-4576-8a33-fdf5d7613af1)

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment] 2024-03-14 05:18
Languages installed in Windows 11 (Although the language mix does not bother me personally, this could be the cause or be related to the failure) 
![image](https://github.com/marticliment/WingetUI/assets/64709446/66b57d95-b2e4-46c9-9011-dbed88f000d2)

**Comment by BePo65** [comment] 2024-03-14 05:41
I have the same effect on a windows 10 pro machine.

**Comment by marticliment** [comment] 2024-03-14 11:39
Duplicate of #1910

**Closed by marticliment** 2024-03-14 11:39 UTC
Labels: bug, ready-to-go
