### ISSUE TITLE
[BUG/ISSUE] (xplicit)

### ISSUE THREAD

**Issue by Chaython** [marticliment/WingetUI#884] opened 2023-04-07 01:15 UTC
## Before submitting the issue

- [ x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x ] **I have checked that I am running the latest version of WingetUI**
- [x ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x ] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [ x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Missing package details?

## To Reproduce
Steps to reproduce the behaviour:

## Screenshots
![image](https://user-images.githubusercontent.com/6486343/230520372-515621d5-2890-4ad8-a357-314e20a8fd69.png)

## The Log
log too long https://pastebin.com/8czV3FBi
<details>

```
Please paste here the log (Go to the three dots menu on the top-right corner of WingetUI -> Winget Log. 

If the issue can be reproduced, please send the log AFTER reproducing the issue (1. Launch WingetUI, 2. Reproduce the issue, 3. Paste the log)
```

</details>

**Comment by kirashi3** [comment] 2023-04-07 04:18
Looks like a duplicate of https://github.com/marticliment/WingetUI/issues/874

**Comment by marticliment** [comment] 2023-04-13 18:32
Fixed!

**Closed** 2023-04-13 18:33 UTC
Labels: bug, ready-to-go, winget
