### ISSUE TITLE
[FEATURE REQUEST] Choose which apps to upgrade automatically

### ISSUE THREAD

**Issue by Eruthon** [marticliment/WingetUI#1450] opened 2023-10-05 06:52 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

I believe this feature would be very helpful to have, as having all programs update automatically is not wished in every use case.
It could be something like a favorites list.

### Describe how this new feature could help users.

Users could create a list of their "favorite" apps to have updated all the time, while other apps which tends to have problematic installations or hash mismatches etc could be excluded from automatic upgrades.

**Comment by ppvnf** [comment] 2023-10-05 20:04
possibly duplicate of https://github.com/marticliment/WingetUI/issues/1383

**Comment by marticliment** [comment] 2023-10-06 15:42
Actually yes, duplicate #1383

**Closed by marticliment** 2023-10-06 15:42 UTC
Labels: new-feature, ready-to-go
