### ISSUE TITLE
[FEATURE REQUEST] Automatically deselect packages in the "Discover" tab after they are installed

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#999] opened 2023-05-03 21:25 UTC
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

Currently, packages aren't deselected after they're installed.

1. Install package 1 by selecting it and pressing install.
2. Install package 2 ''
3. Now, package 1 got reinstalled because you never deselected it.

## Describe the solution you'd like

Automatically deselect packages after they're installed.

**Comment by marticliment** [comment] 2023-05-03 22:24
Duplicate of #810

**Comment by aaronliu0130** [comment] 2023-05-04 00:56
While these are related, they aren't duplicates. Nowhere does the issue mention being deselected when it's installed.

Also, It's either my first time installing multiple software this way, or this hasn't happened in prior versions.

**Comment by marticliment** [comment] 2023-05-04 05:33
ah sorry, I did. not properly understand your request

**Comment by aaronliu0130** [comment] 2023-06-09 00:47
@marticliment At least for scoop packages, this still isn't fixed, though scoop won't reinstall unlike winget.

**Comment by marticliment** [comment] 2023-06-10 19:34
This appears to be fixed in the latest beta

**Closed by marticliment** 2023-06-10 19:34 UTC
Labels: feature-request, ready-to-go
