### ISSUE TITLE
[BUG] WingetUI does not report GodotEngine.GodotEngine as upgradeable, but Winget does

### ISSUE THREAD

**Issue by kriswilk** [marticliment/WingetUI#1519] opened 2023-10-23 15:17 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Winget CLI reports that GodotEngine.GodotEngine is upgradeable from v4.1.1 to v4.1.2. However, WingetUI does not list this package as one of the available upgrades. It appears that WingetUI's call to winget does not list the package for some reason??

### Steps to reproduce the issue

- run "winget upgrade" to enumerate upgradable packages (see screenshot)
- refresh WingetUI software updates list (see screenshot)
- compare the results

### WingetUI Log

```text
🔵 Loading WingetUI log...
🔵 Sending cancel signal...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 5 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 5
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
- 
   \ 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 8.20 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 8.20 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 8.20 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 8.20 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 8.20 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  6.00 MB / 8.20 MB
  █████████████████████████▒▒▒▒▒  7.00 MB / 8.20 MB
  █████████████████████████████▒  8.00 MB / 8.20 MB
  ██████████████████████████████  8.20 MB / 8.20 MB
                                                                                                                        

   - 
                                                                                                                        
Name                                                        Id                          Version    Available  Source
--------------------------------------------------------------------------------------------------------------------
Rclone                                                      Rclone.Rclone               1.64.0     1.64.2     winget
Microsoft Visual C++ 2010  x86 Redistributable - 10.0.30319 Microsoft.VCRedist.2010.x86 10.0.30319 10.0.40219 winget
Prowlarr version 1.8.6                                      TeamProwlarr.Prowlarr       1.8.6      1.8.6.3946 winget
Radarr version 4.7.5                                        TeamRadarr.Radarr           4.7.5      5.0.3      winget
Lidarr version 1.3.5                                        TeamLidarr.Lidarr           1.3.5      1.3.5.3530 winget
5 upgrades available.
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/382436/8ad66f5f-e6e5-46c6-bfc6-fc1de8985064)

![image](https://github.com/marticliment/WingetUI/assets/382436/538ef4c8-27e5-4574-acc8-9a4e30590c7e)

**Comment by marticliment** [comment] 2023-10-23 15:20
Hello @kriswilk,

WingetUI's winget does not seem to be detecting GodotEngine.

Which winget version are you running on the system? Which WingetUI version?
Have you tried forcing a reload of the winget sources via winget update, using wingetui's bundled winget?

**Comment by kriswilk** [comment] 2023-10-23 16:39
winget version reported at CLI: v1.7.2782-preview
WingetUI version: 2.1.1

Interestingly, WingetUI about box indicates winget "found" at version 1.6.2771. I'm guessing this is part of the problem. Does WingetUI bundle its own version of winget? I don't know how I could possibly have two versions. It's a new PC running Windows 11 with all updates. No insider previews or anything strange.

![image](https://github.com/marticliment/WingetUI/assets/382436/3eef2845-ce1b-42e7-8497-9f2762f92371)

**Comment by kriswilk** [comment] 2023-10-23 16:42
As a follow-up...I just looked in WingetUI settings and see that yes, you do bundle your own copy of winget (why...is this so users don't even need to install winget in the first place?). I tried clicking the "reset winget sources" button and then refreshed the package list, but nothing changed.

**Comment by marticliment** [comment] 2023-10-23 20:23
> is this so users don't even need to install winget in the first place?

No, this is to prevent winget localisation from breaking parsing mechanisms. The bundled version of winget does not include translation files.



> I tried clicking the "reset winget sources" button and then refreshed the package list, but nothing changed.

On my WingetUI install I can see godot version 4.1.2 showing up (running on winget 1.6), so winget or wingetui themselves are not the cause.
Winget 1.6 involves a new feature named package list caching to prevent winget server overloading, so your installation might just be waiting for a timeout before truly fetching the package indexes (despite you calling winget update.) You can read more about that change here: https://github.com/microsoft/winget-cli/pull/3718

**Comment by kriswilk** [comment] 2023-10-25 13:26
It's been days without change. I don't think that has anything to do with this. To test further, I used Terminal to run the WingetUI-bundled winget to show me package info for Godot:

```
PS C:\Program Files\WingetUI\PackageManagers\winget-cli_x64> .\winget show godotengine.godotengine
Found Godot Engine [GodotEngine.GodotEngine]
Version: 4.1.2
Publisher: Godot Engine
Publisher Url: https://godotengine.org
Publisher Support Url: https://github.com/godotengine/godot/issues
Description: Multi-platform 2D and 3D game engine
Homepage: https://github.com/godotengine/godot
License: MIT License
License Url: https://github.com/godotengine/godot/blob/master/LICENSE.txt
Release Notes:
  - Release notes
  - Curated changelog
  - Download (GitHub): Expand Assets below
Release Notes Url: https://github.com/godotengine/godot/releases/tag/4.1.2-stable
Installer:
  Installer Type: portable (zip)
  Installer Url: https://github.com/godotengine/godot/releases/download/4.1.2-stable/Godot_v4.1.2-stable_win64.exe.zip
  Installer SHA256: 4bcc449aae8ea10280e2bf2be3da02f7da6b86f3265d337428e847e0ecd8704d
  Release Date: 2023-10-04
PS C:\Program Files\WingetUI\PackageManagers\winget-cli_x64>
```

As you can see, WingetUI's version of winget clearly knows about the new version 4.1.2. Yet using it to run `winget upgrade` yields:

```
PS C:\Program Files\WingetUI\PackageManagers\winget-cli_x64> .\winget upgrade
Name                                                        Id                          Version       Available      Source
---------------------------------------------------------------------------------------------------------------------------
Rclone                                                      Rclone.Rclone               1.64.0        1.64.2         winget
Microsoft Visual C++ 2010  x86 Redistributable - 10.0.30319 Microsoft.VCRedist.2010.x86 10.0.30319    10.0.40219     winget
Prowlarr version 1.8.6                                      TeamProwlarr.Prowlarr       1.8.6         1.8.6.3946     winget
Google Chrome                                               Google.Chrome               118.0.5993.89 118.0.5993.118 winget
Radarr version 4.7.5                                        TeamRadarr.Radarr           4.7.5         5.0.3          winget
Lidarr version 1.3.5                                        TeamLidarr.Lidarr           1.3.5         1.3.5.3530     winget
6 upgrades available.
PS C:\Program Files\WingetUI\PackageManagers\winget-cli_x64>
```

Lastly, I made sure WingetUI's winget knew that Godot 4.1.1 was already installed:

```
Name                                           Id                                                            Version          Source
-------------------------------------------------------------------------------------------------------------------------------------
<other items clipped for brevity>
Beyond Compare 4.4.6                           ScooterSoftware.BeyondCompare4                                4.4.6.27483      winget
Microsoft Clipchamp                            Clipchamp.Clipchamp_yxz26nhyzhsrt                             2.8.1.0
Colors                                         den4b.Colors                                                  3.1.0.0          winget
FreeCAD 0.21.1 (Installed for Current User)    FreeCAD.FreeCAD                                               0.21.1           winget
GIMP 2.10.34-2                                 GIMP.GIMP                                                     2.10.34          winget
Git                                            Git.Git                                                       2.42.0.2         winget
Godot Engine                                   GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe 4.1.1
HWiNFO64 Version 7.64                          REALiX.HWiNFO                                                 7.64             winget
Hack Fonts version 1.6.0                       SourceFoundry.HackFonts                                       1.6.0            winget
Hasher                                         den4b.Hasher                                                  4.1.0.0          winget
<other items clipped for brevity>
PS C:\Program Files\WingetUI\PackageManagers\winget-cli_x64>
```

On one hand, winget knows what version is installed AND knows that there is a new version. On the other hand, it's not offering to upgrade it.

I realize WingetUI is just acting on the results of this bundled winget, but if it's happening to me, who knows what other packages are affected.

Ideas??

**Comment by marticliment** [comment] 2023-10-25 14:39
I don't know why Godot is being reported as `GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe`, but this is likely the cause of thisissue, since the available package from the repo is "GodotEngine.GodotEngine", and GodotEngine.GodotEngine is detected as v4.1.2.

Please try installing GodotEngine 4.1.2 from WingetUI (or from bundled winget) to force an update, and post back which package id is and version are reported on the InstalledPackages tab.

**Comment by marticliment** [comment] 2023-10-26 08:08
I will close this, since it is an issue that happened one time only, and also since this is ultimately a winget bug, not a WingetUI one. 

However, if more cases of this issue appear i'll reopen it. 
If you happen to experience it again, please let me know

**Closed by marticliment** 2023-10-26 08:08 UTC
Labels: bug, needs-author-answer
