### ISSUE TITLE
Option to see where a program is installed

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1542] opened 2023-11-01 03:39 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

It would be very useful to be able to see the file location where a program has been installed under both "Installed Packages" and most importantly under "Software Updates". THis will help the user evaluate if he should apply an update, or just "Ignore updates for this package" instead.

This is very handy for programs/packages that have been installed and bundled with another software suite. Then there might be version requirements, and updating might break something. So it's better left to the installer or update function of the "main software suite" to handle updates (might still happen through Winget/WingetUI but by updating the "main software suite" instead),

An example could be MS Visual Studio, it will install several other packages through it's own installer, and in a location "belonging" to MS Visual Studio. Those are best left to the MS Visual Studio installer to update.

There are others as well, I have a few music and video editing suites (currently not on winget) that have installed one or more other programs that are available through Winget. I don't want to upgrade those, and it would be easier to spot them if I had the file location available in WingetUI.

### Describe how this improvement could help users.

Described above :)

**Comment by marticliment** [comment] 2023-11-01 13:13
This is the same idea of #1386, right?

**Comment by chjohans** [comment] 2023-11-01 13:59
Sorry,I did a search but must have missed that one. Yes, but I don't necessarily suggest to "go to" the install folder, just seeing where it is would be sufficient in my opinion. But about the same, yes.

**Comment by marticliment** [comment] 2023-11-01 15:02
I'm going to mark this as duplicate then. Both features require the same code to work.

duplicate of #1386

**Closed by marticliment** 2023-11-01 15:02 UTC
Labels: enhancement
