### ISSUE TITLE
[Favorites] (Allow installs to be marked as a Favorite which always gets updated)

### ISSUE THREAD

**Issue by AdamsTaiwan** [marticliment/WingetUI#2337] opened 2024-06-24 05:04 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

I propose a "Favorites" button be added to the 4 buttons on the top left can be viewed. These can be run manually or automatically for any install selected as a Favorite.

### Describe how this new feature could help users.

While "Ignore updates" is a good feature, it also means that one must select this for all apps. However, one might still want to have this list to view.  So it is easy to select maybe 4 favorites to update, than 100 to ignore.

**Comment by marticliment** [comment] 2024-06-24 20:53
duplicate of https://github.com/marticliment/WingetUI/issues/1383

**Closed by marticliment** 2024-06-24 20:53 UTC
Labels: new-feature
