### ISSUE TITLE
[BUG] Window size and position is reset after restart of WingetUI

### ISSUE THREAD

**Issue by min7-i** [marticliment/WingetUI#1866] opened 2024-03-06 21:07 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When repositioning and resizing the window, this is only remembered while WingetUI is open or minimized and reopened. After restarting WingetUI, however, the window position and size is reset.

### Steps to reproduce the issue

1. Change the window size and position.
2. Close the program.
3. Restart it.
4. Check the size and position of the window.

### WingetUI Log

```text
N/A - If you need the logs, just let me know.
```

### Package Managers Logs

```text
N/A - If you need the logs, just let me know.
```

### Relevant information

This happens on two Win10 computers both of which have WingetUI 3.0.0 Beta 0 installed.

**Comment by mahara** [comment] 2024-03-24 19:38
In addition, can last selected navigation tab (Discover Packages, Software Updates, etc.) also be remembered/persisted?

**Comment by tnilzon** [comment] 2024-04-18 08:40
Quite annoying. Hope this will be fixed soon, thanks.

OS Name: Microsoft Windows 11 Pro, v10.0.22631 Build 22631
WingetUI v3.0.2

**Comment by WalterB-MAMC** [comment] 2024-05-01 21:42
I have ultrawide monitor and this is very annoying as it opens up very wide. Must be set to use x% of screen on open. I have to shrink it a lot as the width is crazy. Then when I open the app again to check, wham super larger again.

**Comment by infuriatedcodex** [comment] 2024-05-07 10:23
> I have ultrawide monitor and this is very annoying as it opens up very wide. Must be set to use x% of screen on open. I have to shrink it a lot as the width is crazy. Then when I open the app again to check, wham super larger again.

Confirmed, this happens to mine too.
Screen Res is 5120x1440 and on restart of the app, it opens at 3826x1016

**Comment by ishvedov** [comment] 2024-05-20 14:53
Annoying thing. The same problem.

**Comment by Basti-Fantasti** [comment] 2024-05-31 06:04
Yes please fix/modify this, very annoying behaviour on ultra wide screens.

**Comment by ishvedov** [comment] 2024-06-05 01:27
@marticliment, position only saved while resizing. If I just move window, position does not saved.

**Comment by marticliment** [comment] 2024-06-05 06:47
Hi @ishvedov, position is only saved when resizing the window or when closing it. As far as I have been able to find, apparently there is no way to detect when a window has been moved across the desktop

**Comment by ishvedov** [comment] 2024-06-05 14:34
It's does not save on exit. I'm using 3.1.0 alpha 1.

**Comment by aaronliu0130** [comment] 2024-06-05 15:03
Maybe we could try https://stackoverflow.com/questions/10330470/c-sharp-window-positioning?

**Comment by marticliment** [comment] 2024-06-05 15:27
This is Windows Forms, UniGetUI is built with WinUI3, which has nothing to do with WinForms

**Comment by marticliment** [comment] 2024-06-05 15:33
No, the issue is not with moving the actual window, since this is quite doable. The issue is when detecting when a window has been dragged by the user

**Comment by marticliment** [comment] 2024-06-05 15:38
That is what actually happens, but it seems to not be working properly for @ishvedov

**Comment by siewers** [comment] 2024-06-05 15:41
Sorry, yes you're right, I should have read the thread.
I haven't tested the alpha version yet, but I'll try to reproduce it later.

**Comment by siewers** [comment] 2024-06-05 18:04
I cannot reproduce this on 3.1.0 alpha 1.
- closing the window (minimizing to tray) - works
- closing the window (minimizing to tray), right-click to quit - works
- right-click to quit with window open - works

@ishvedov Is the window completely reset each time you start the application, or does it only/also happen when you restore it from the tray?

**Comment by ishvedov** [comment] 2024-06-05 20:29
I build app from main branch. This line have a problem. Process exits. If I comment this line, all works as expected.

https://github.com/marticliment/WingetUI/blob/d3521feed774363057a555a0d8d1e06f7165620b/src/UniGetUI/Interface/MainWindow.xaml.cs#L484C13-L484C19

**Comment by marticliment** [comment] 2024-06-05 20:32
This line should not have a problem... It is a simple wait command. 

Which NET version are you using? Which Visual Studio?

**Comment by ishvedov** [comment] 2024-06-05 20:43
I know it, but...
SDK 9.0.100-preview.4.24267.66
SDK 8.0.300
Visual Studio 17.11 preview 1.1
Dotnet runtime for UnigetUI: 8.0.6

**Comment by marticliment** [comment] 2024-06-05 20:55
I don't see why it wouls crash on that line... Which is the error triggered? the thread crashes? The code does not compile?

**Comment by ishvedov** [comment] 2024-06-05 21:46
Problem with `Delay` in handle of `Closing` event. I add `Task.Delay` to event handler, and app exit too on this line.

**Comment by marticliment** [comment] 2024-06-06 07:03
Oh, I see what the issue is now

**Closed** 2024-06-06 14:19 UTC
Labels: bug, ready-to-go, beta
