### ISSUE TITLE
[BUG/ISSUE] Winget version parsing is being trimmed if it's more than one string 

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#823] opened 2023-03-19 23:40 UTC
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
There seem to be a bug with parsing the version of a package which it's version is consisting of two string separated by a space

## To Reproduce
Steps to reproduce the behaviour:
1. Go to the "Discover Packages"
2. Click on the Version text in the first row to sort it so it will show like that:
![image](https://user-images.githubusercontent.com/8223772/226216714-48e74d0b-ad6d-406c-bb5a-22a7833b61ae.png)
3. This is a trimmed text of the full version string
4. Verify that by showing info of this package, you can clearly see that it is being trimmed:
![image](https://user-images.githubusercontent.com/8223772/226216929-b74d45e9-bc34-43f0-9097-22becb0adbe5.png)

Info about the package from winget:
![image](https://user-images.githubusercontent.com/8223772/226217712-afa458ea-b42a-4ce4-a512-a9b6378ecd5f.png)

## Expected behaviour
Package version shows "WIA-Loader 2.7.30" in the table (not trimmed)

**Please note that I don't think that this is the same bug as in #805**

**Comment by marticliment** [comment] 2023-03-20 18:13
This is an issue actually caused by Winget.exe, that is that when using winget search *, longer texts are trimmed instead of shwon completely. 

This issue can't be fixed, but it might get resolved with the implementation of #712 (we would get rid of console parsing)

**Comment by Mikey1993** [comment] 2023-03-20 20:23
> This is an issue actually caused by Winget.exe, that is that when using winget search *, longer texts are trimmed instead of shwon completely.
> 
> This issue can't be fixed, but it might get resolved with the implementation of #712 (we would get rid of console parsing)

How so is that a problem with winget.exe output?
This is what I get:
![image](https://user-images.githubusercontent.com/8223772/226456778-d1e07e2e-c712-4d34-a304-4b8bf99d0494.png)

Per https://learn.microsoft.com/en-us/windows/package-manager/winget/search it says:
![image](https://user-images.githubusercontent.com/8223772/226456956-1f5c81d2-7a61-496b-b807-547d24d602d5.png)

**Comment by marticliment** [comment] 2023-03-20 20:29
It behaves like this:
![image](https://user-images.githubusercontent.com/53119851/226458293-ad07bd99-c300-47ef-b0d7-3e18a87f0234.png)



See #196 for further details

**Closed** 2023-03-20 20:29 UTC
Labels: bug

**Comment by Mikey1993** [comment] 2023-03-20 20:42
But it doesn't seem to affect this package as I see the version and the app name fully, so how is it related to this bug?

Also, seems like with the new winget-cli v1.5, there will be better handling of version through the `winget search` command:
https://github.com/microsoft/winget-cli/pull/2847

**Comment by marticliment** [comment] 2023-03-20 20:47
When showing few packages, winget adapts its width to the full length. When showing all packages, it does not.

This is an open issue in winget's repository

**Comment by ppvnf** [comment] 2023-03-20 20:54
hopefully v1.5 will fix it

https://github.com/microsoft/winget-cli/issues/2603

**Comment by Mikey1993** [comment] 2023-03-20 20:57
> When showing few packages, winget adapts its width to the full length. When showing all packages, it does not.
> 
> This is an open issue in winget's repository

Can 't believe that even a simple output format (like JSON for example) is not available for proper parsing these days.
