### ISSUE TITLE
[ENHANCEMENT] Avoid Displaying Quickly Vanishing Command Prompts Per Update

### ISSUE THREAD

**Issue by D-Maxwell** [marticliment/WingetUI#2030] opened 2024-03-23 18:40 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

For some reason --i am unable to tell what those are for-- command prompts get opened every time UnigetUI begins working on a new task.

### Describe how this improvement could help users.

Those are quite distracting ; especially since --on top of flashing on my screen-- they take away keyboard focus.

**Comment by marticliment** [comment] 2024-03-24 11:06
Which packages do present this issue? All of them? Or only the packages from one specific source?

**Comment by marticliment** [comment] 2024-03-25 10:19
Duplicate of #2036

**Closed by marticliment** 2024-03-25 10:19 UTC
Labels: needs-author-answer, enhancement
