### ISSUE TITLE
[ENHANCEMENT] (Enter your description here)

### ISSUE THREAD

**Issue by aramaicus** [marticliment/WingetUI#1466] opened 2023-10-09 06:25 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

When you click on the search box, it doesn't show any visual indication that you have selected the box, such as a cursor or highlight.

In the video I shared, you can see that when I click on the search box, there is no cursor or highlight to indicate it is selected. This makes it a bit confusing from a usability standpoint.

https://github.com/marticliment/WingetUI/assets/84055541/ae7f7acd-b8ce-4f13-a49b-aabcdf783ee4

### Describe how this improvement could help users.

Clear visual indicators when a text field is selected are important for usability. Without any highlight or cursor shown on click, users may not realize the search box is ready for input. They may think the app is non-responsive or frozen.

Adding a subtle highlight color and/or cursor on selection will provide that crucial feedback that the search box is active and ready to accept text input. This helps guide the user experience and prevents confusion. Users will know their click was registered, and they can immediately begin typing a search query.

Overall, this minor enhancement takes something that is currently ambiguous and makes it unambiguous. The user no longer has to guess if their click worked. This improves the perceived responsiveness of the app, reduces confusion, and makes the search function more intuitive. It's a small change that goes a long way in refining the UX.

**Comment by marticliment** [comment] 2023-10-09 14:53
This is a duplicate of issue #115

**Closed** 2023-10-09 14:54 UTC
Labels: enhancement
