### ISSUE TITLE
[CHOCO] Missing package

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#905] opened 2023-04-11 16:20 UTC
https://community.chocolatey.org/packages/bitwarden#versionhistory
<img width="938" alt="Screenshot 2023-04-11 181736" src="https://user-images.githubusercontent.com/73800734/231226034-a001e80d-e736-400d-9716-411198d3efb3.png">
<img width="660" alt="Screenshot 2023-04-11 181801" src="https://user-images.githubusercontent.com/73800734/231226038-cff0cd36-ebf4-4f32-aaac-b3949baf9351.png">
I am not sure what the message besides the package means, but it seems to affect WingetUI ability to load it

**Comment by marticliment** [comment] 2023-04-11 17:44
can you please try temporarily disabling winget and scoop and try to search again for bitwarden?

**Comment by marticliment** [comment] 2023-04-11 20:07
It does indeed appear in the cached packages
![image](https://user-images.githubusercontent.com/53119851/231276677-a39dc255-2009-45ce-8917-210388eca940.png)

My best guess is that it is conflicting with the scoop package named in the same way.

**Comment by marticliment** [comment] 2023-04-13 18:52
After some changes, it now appears for me in the latest head. Could you please test it out?

**Comment by ppvnf** [comment] 2023-04-13 18:56
I don't know how I can test it out, because after doing what you said in https://github.com/marticliment/WingetUI/issues/905#issuecomment-1503834472 the bug didn't come back in version 1.6.5, even after reenabling Winget/Scoop

**Comment by marticliment** [comment] 2023-04-13 19:18
It should now be fixed (the issue regarding multiple same ids shouldn't happen again). I'll close this, since for me it got fixed after messing with the code. If the issue reappears, please let me know and i'll reoprn this

**Comment by ppvnf** [comment] 2023-04-20 22:03
the bug happened again in the latest beta:

<img width="923" alt="Screenshot 2023-04-21 000223" src="https://user-images.githubusercontent.com/73800734/233496948-d27ba00a-6f1a-470b-b86e-1d3dccc16ea6.png">

**Comment by ppvnf** [comment] 2023-04-21 15:53
After I tested today's version the bug was gone somehow

**Comment by marticliment** [comment] 2023-04-21 16:26
this might be an intermittent bug somehow.

**Comment by ppvnf** [comment] 2023-04-23 15:21
> It appears in the cached packages 
> 
> My best guess is that it is conflicting with the scoop package named in the same way.

how can I see the cached packages?

**Comment by marticliment** [comment] 2023-04-23 15:25
Winget and scoop packages are not stored in a file, but rather in a dictionary in the code itself. 

They are never stored in the drive.

However, chocolatey packages are stored here: C:\Users\user\.wingetui\cacheddata

**Comment by ppvnf** [comment] 2023-04-23 18:52
there is something strange with this cache in my computer I think:
the old one I had from previous versions is missing Bitwarden and has a strange error message. If I delete it a new one is created containing Bitwarden but missing quite a few packages

[chocolateypackages_old.txt](https://github.com/marticliment/WingetUI/files/11304607/chocolateypackages_old.txt)
[chocolateypackages.txt](https://github.com/marticliment/WingetUI/files/11304608/chocolateypackages.txt)

**Comment by marticliment** [comment] 2023-04-23 18:56
> If I delete it a new one is created containing Bitwarden but missing quite a few packages
This issue is due to choco list * nit listing all the packages, but durther updates do progressively add the missing packages, so they might not appear at the start, but shown packages should not disappear

**Comment by ppvnf** [comment] 2023-04-29 11:41
> This issue is due to choco list * nit listing all the packages, but durther updates do progressively add the missing packages, so they might not appear at the start, but shown packages should not disappear

I would rather wait the first time WingetUI loaded and have all packages

**Comment by marticliment** [comment] 2023-04-29 11:56
The issue is that one single run can take up to 10 minutes, and running the command again won't fully complete the list.
Most of the time running the command again will return a way smaller list of packages.

**Comment by ppvnf** [comment] 2023-05-01 11:31
Since 1.7 stable was release I am not longer getting this error but I will continue checking it out for a few more days

**Comment by ppvnf** [comment] 2023-05-04 08:53
I just did a test today and It still disappears from the list it seems. Also, I have installed WingetUI on a friends's PC and I had to restart it for the Chocolatey packages to show up (it kept loading for a long time). Unfortunatelly I can't reproduce this on my own PC since I don't have enough RAM to rum VMs

**Comment by R4ygen** [comment] 2023-05-05 05:58
Hello, novice user here, just installed WingetUI on two newly formatted PCs with Windows 11, and I'm getting the same issue.
WingetUI is missing packages from chocolatey, that do get found by searching them with `chocolatey search <name>`.
One of these packages is: `wssc` or `windowssystemcontrolcenter`.

**Comment by serrj-sv** [comment] 2023-05-05 10:39
Hi, I have same issue, but with scoop. Freshly installed latest WingetUI 1.7.1
WingetUI is missing packages from scoop entirely (in Discovery Packages), until I temporary disable and then re-enable winget, as advised in https://github.com/marticliment/WingetUI/issues/905#issuecomment-1503834472

**Comment by R4ygen** [comment] 2023-05-05 15:13
> Hi, I have same issue, but with scoop. Freshly installed latest WingetUI 1.7.1 WingetUI is missing packages from scoop entirely (in Discovery Packages), until I temporary disable and then re-enable winget, as advised in [#905 (comment)](https://github.com/marticliment/WingetUI/issues/905#issuecomment-1503834472)

Right, I got issues with scoop too, but managed to fix it by uninstalling scoop from WingetUI and installing it natively via shell. Followed by `scoop update` and `scoop checkup` commands, and following the errors and instructions that would pop out. Enabling it and manually adding the `main` and `extras` buckets in WingetUI at the end.

[#905](https://github.com/marticliment/WingetUI/issues/905#issuecomment-1503834472) did not fixed scoop for me sadly. Everytime I would try to re-enable scoop in the settings, and restart WingetUI, it would revert back to disabled.

For fancies, I've tried to do the same with chocolatey: uninstall it from WingetUI and installing it natively via shell, followed by the `choco unpackself` command and re-enabling it in WingetUI. But it did not fix the missing packages issue in WingetUI.

**Comment by ppvnf** [comment] 2023-05-16 20:18
in version 2.0 (beta 2) I haven't encountered this bug again. About the Scoop bug reported by  [R4ygen](https://github.com/R4ygen) and [serrj-sv](https://github.com/serrj-sv), I believe it is related to https://github.com/marticliment/WingetUI/issues/867.

**Comment by marticliment** [comment] 2023-06-13 10:46
Is this issue still present for you?

I can't reproduce it anymore with the latest code...

**Comment by ppvnf** [comment] 2023-06-13 13:01
I am on beta 3. Currently the bug is not happening, but on the same version it was happening last week. Are you able to compare that it happens in the previous version, but not on the latest? I don't know how to

**Comment by marticliment** [comment] 2023-06-13 13:31
No, I just found all packages working with this version. 

I will continue to investigate this

**Comment by R4ygen** [comment] 2023-06-17 13:35
> Is this issue still present for you?
> 
> I can't reproduce it anymore with the latest code...

Hello, just updated to 2.0.1 and the same Choco packages are still missing for me. The issue is reproducible on 2 different machines.
I've treid to reset WingetUI from the settings after the update, no change.

**Closed** 2023-09-01 16:49 UTC
Labels: bug, ready-to-go, important, scoop, chocolatey
