### ISSUE TITLE
[ENHANCEMENT] Provide tooltips for toolbar buttons

### ISSUE THREAD

**Issue by rjwut** [marticliment/WingetUI#1569] opened 2023-11-17 22:07 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

This is how the toolbar looks now:

![image](https://github.com/marticliment/WingetUI/assets/5790951/91d19de0-3ffc-4e02-9853-a63e5d9fbd03)

Some buttons have text labels, but most don't. It may not be clear to the user what some of these buttons do, and it's not obvious that you can right-click on a line item to get a list of actions with the corresponding icons. It would be helpful if WingetUI would show a tooltip when you hover the mouse over a button.

### Describe how this improvement could help users.

It would make it easier for users to discover the purpose of toolbar buttons.

**Comment by marticliment** [comment] 2023-11-17 22:11
This issue has already been fixed, and the next version will contain those tooltips (duplicate of #1410 )

**Closed by marticliment** 2023-11-17 22:11 UTC
Labels: enhancement

**Comment by rjwut** [comment] 2023-11-17 22:54
Oh, cool, thank you! Sorry I missed that.
