### ISSUE TITLE
[BUG] (winget 0x800f024b)

### ISSUE THREAD

**Issue by LittleFreak** [marticliment/WingetUI#1544] opened 2023-11-01 15:57 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

WingetUI shows no winget packages in the installed section, nevertheless in the discovery.
This Issue occurs with the system and the native `winget.exe`, although there is a little difference...

When I use the **native** variant, the sources list in the settings fails to load. Any attempt to reset this results in 0x800f024b.

Those sources are visible with the **system variant** enabled, but the packages list still refuses to show any winget package.

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.002995729446411133 to load all language files
🟢 checkQueue Thread started!
🔵 Found default chocolatey installation on expected location
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1698853080.8664987]
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetu...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.4.1-fixnoninteractive (Branch.tags-v2.4.1-fixnoninteractive.Sha.dab0a3eda989972d4df8e08cc1b7d68422652e61)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop ist deaktiviert', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey ist deaktiviert', 'PipFound': False, 'PipVersion': 'Pip ist deaktiviert', 'NpmFound': False, 'NpmVersion': 'Npm ist deaktiviert', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool ist deaktiviert', 'WingetFound': True, 'WingetVersion': 'v1.6.2771  '}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Starting winget source search...
🟢 Starting winget source search...
🟢 Settings tab loaded!
🟢 winget source search finished
🟢 winget source search finished
🟢 About tab loaded!
🟢 Main application loaded...
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Searching for string "t"
🟢 Searching for string "te"
🟢 Searching for string "tes"
🟢 Searching for string "test"
🔵 Loading dynamic packages for query test
🔵 Starting Winget search for dynamic packages
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string "test"
🔵 Loading operation log...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x800f024b : Der Hashwert für die Datei ist in der angegebenen Katalogdatei nicht vorhanden. Die Datei ist wahrscheinlich beschädigt oder wurde unerlaubt geändert.
---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x800f024b : Der Hashwert für die Datei ist in der angegebenen Katalogdatei nicht vorhanden. Die Datei ist wahrscheinlich beschädigt oder wurde unerlaubt geändert.

---------Winget
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x800f024b : Der Hashwert für die Datei ist in der angegebenen Katalogdatei nicht vorhanden. Die Datei ist wahrscheinlich beschädigt oder wurde unerlaubt geändert.
---------Winget

---------Winget

------- Winget query testFailed when opening source(s); try the 'source reset' command if the problem persists.An unexpected error occurred while executing the command:0x800f024b : Der Hashwert für die Datei ist in der angegebenen Katalogdatei nicht vorhanden. Die Datei ist wahrscheinlich beschädigt oder wurde unerlaubt geändert.
```

### Relevant information

When I try to reset the winget from your package, i get an error message:
`This script will reset winget sources.
. Please wait...
winget path: "C:\Program Files\WingetUI\resources\..\winget-cli\PackageManagers\winget-cli_x64\winget.exe"
Performing reset...
An unexpected error occurred while executing the command:
0x800f024b : Der Hashwert für die Datei ist in der angegebenen Katalogdatei nicht vorhanden. Die Datei ist wahrscheinlich beschädigt oder wurde unerlaubt geändert.
An unexpected error occurred while executing the command:
0x800f024b : Der Hashwert für die Datei ist in der angegebenen Katalogdatei nicht vorhanden. Die Datei ist wahrscheinlich beschädigt oder wurde unerlaubt geändert.
Resetting all sources...Done
Info: Cache session closed.
Task completed!`
I can still install programs via winget in porwershell etc.

**Comment by marticliment** [comment] 2023-11-01 16:08
Which WingetUI version are you using?

**Comment by LittleFreak** [comment] 2023-11-01 20:05
> Which WingetUI version are you using?

the latest- 2.1.1

**Comment by marticliment** [comment] 2023-11-02 09:45
Hello,

I am afraid something is happening with winget-cli, which is the executable in charge of managing the packages. Have you tried reinstalling WingetUI? This behaviour could be caused by corrupt sources...

**Comment by LittleFreak** [comment] 2023-11-02 11:09
I've already re-installed WingetUI given by the release page. Unfortunately this wont help neither.

**Comment by marticliment** [comment] 2023-11-02 12:11
I am afraid this is not an issue with WingetUI itself, but rather with winget-cli. This issue has been reported on their repository (https://github.com/microsoft/winget-cli/issues/3566), I would appreciate if you could post the details there.

**Comment by marticliment** [comment] 2023-11-02 14:40
> I wonder why I cant access the system winget with wingetui, because it just works fine, when I access winget via powershell

This happens due to winget being localised. Therefore, if winget isn't in english parsing breaks.

**Comment by LittleFreak** [comment] 2023-11-02 18:47
So I could switch to the English windows UI, and wingetui will work together with the system cli?

**Comment by marticliment** [comment] 2023-11-02 19:57
It should work, yes

**Comment by seta-hailuong** [comment] 2023-11-13 13:48
I'vs just hit this issue, my solution is use System winget instead of bundle one, you can find it in `Experimental setting and developer option`

**Comment by marticliment** [comment] 2023-12-02 17:51
Hello,

I am going to close this issue, since it is caused by winget-cli  and MS Defender, and not by WingetUI

**Closed by marticliment** 2023-12-02 17:51 UTC
Labels: bug, needs-author-answer

**Comment by DBinK** [comment] 2024-03-09 12:13
> 将本地用户帐户迁移到 Entra ID（以前称为 Azure AD）帐户后，我在 Winget CLI 中收到相同的错误。我能够使用以下 Powershell 命令解决它： `Get-AppxPackage Microsoft.DesktopAppInstaller | Reset-AppxPackage`

thx, it work
