### ISSUE TITLE
[BUG] (no packages shown in Installed/Discover Packages)

### ISSUE THREAD

**Issue by ashes-xda** [marticliment/WingetUI#1190] opened 2023-06-30 18:23 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

No packages are being listed in Discover & Installed packages section i have installed many packages but it only shows "chocolatey" only as you can see in screen recording

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.004999637603759766 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🔵 Reloading Winget sources...
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', 'WingetFound': True, 'WingetVersion': 'v1.5.1572\r', 'PipFound': True, 'PipVersion': '', 'ChocolateyFound': True, 'ChocolateyVersion': '1.4.0\r'}
🔵 Reached main ui load milestone
🔵 Is Dark
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🟠 Winget cache file exists but is empty!
🔵 Starting Winget package caching
🔵 Starting Chocolatey search for available packages
🟢 Found valid, non-empty cache file for Chocolatey!
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 1004 result(s)
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Winget packages cached successfuly
🔵 Starting Winget search for available packages
🟠 Winget cache file exists but is empty!
🔴 Could not load Winget packages, returning an empty list!
🟢 Install tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🟢 Searching for string ""
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Pip search for installed packages finished with 0 result(s)
🔵 Starting Chocolatey search for updates
🔵 Starting Winget search for updates
🔵 Starting Pip search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Pip search for updates finished with 0 result(s)
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Main application loaded...
🟢 Chocolatey search for updates finished with 0 result(s)
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Pip search for installed packages finished with 0 result(s)
🟢 Total packages: 1003
🟢 Total packages: 1003
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 2
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Pip search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 1
🔵 Starting Winget search for available packages
🟠 Winget cache file exists but is empty!
🔵 Starting Winget package caching
🔵 Starting Chocolatey search for available packages
🟢 Found valid, non-empty cache file for Chocolatey!
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 1004 result(s)
🟢 Winget packages cached successfuly
🔵 Starting Winget search for available packages
🟠 Winget cache file exists but is empty!
🔴 Could not load Winget packages, returning an empty list!
🟢 Total packages: 1003
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Pip search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 1
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🔵 Starting Pip search for installed packages
🟢 Searching for string ""
🟢 Pip search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 1
🔵 Loading log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt---------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
---------
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

---------
Chocolatey v1.4.0
0 packages installed.

---------
Chocolatey v1.4.0
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.---------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
---------
Chocolatey v1.4.0
0 packages installed.
---------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
---------
Chocolatey v1.4.0
0 packages installed.

Did you know Pro / Business automatically syncs with Programs and
Features? Learn more about Package Synchronizer at
https://chocolatey.org/compare---------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt

---------
Chocolatey v1.4.0
0 packages installed.
---------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000b : The configured source information is corrupt
---------
Chocolatey v1.4.0
0 packages installed.
```

### Relevant information

 #1007 similar issue which is said to be solved by the developer but I'm still facing this in latest version
WinGet version 2.0.1

### Screenshots and videos

https://github.com/marticliment/WingetUI/assets/24289410/7f6c567a-73a1-4fda-818f-6810d2b1d50c

**Comment by marticliment** [comment] 2023-07-01 10:40
Hello @ashes-xda,

A few things:
 - Can you please post here your user directory?
 - On the discover packages section, can you please searching for something?
 - regarding chocolatey, did you have chocolatey installed before installing WingetUI?
 - Have you tried resetting winget sources from WingetUI settings?

**Comment by Pipixel** [comment] 2023-07-01 15:39
To get the program list on "Discover Package", you have to check "List packages if the query is empty on the Discover tab"

![image](https://github.com/marticliment/WingetUI/assets/66361896/4952865c-a438-4796-bbee-850cbda2ac35)

**Comment by Pipixel** [comment] 2023-07-02 14:42
I got the same issue thrice, it's in random circumstances. It can be by restart or without interactions.

**Comment by marticliment** [comment] 2023-07-02 18:07
The issue regarding missing packages is related to #1194.

As state by @Pipixel, if packages are "missing" in the discover section either a search should be done or package listing on startup should be enabled

**Comment by marticliment** [comment] 2023-07-02 18:08
I am going to close this issue as duplicate in favour of #1194

**Closed by marticliment** 2023-07-02 18:08 UTC
Labels: bug, needs-author-answer

**Comment by ashes-xda** [comment] 2023-07-02 18:31
@marticliment 
1. This is the directory  `C:\Users\akash\AppData\Local\Programs\WingetUI`
2. Searching is working
3. Yes i had chocolatey already before WIngetUI
4. Yes tried resetting as well as re-installing but no success
sorry for late reply

**Comment by ashes-xda** [comment] 2023-07-02 18:50
@Pipixel this solved my Discover Packages issue after enabling it but packages in installed section are still now showing up

**Comment by marticliment** [comment] 2023-07-02 21:40
> * Yes i had chocolatey already before WIngetUI

Do you have the option "Use system chocolatey" enabled?

**Comment by ashes-xda** [comment] 2023-07-03 10:12
> > * Yes i had chocolatey already before WIngetUI
> 
> Do you have the option "Use system chocolatey" enabled?

@marticliment no.... but after enabling it chocolatey version got changed from 1.4.0 to 2.1.0 that's it

**Comment by marticliment** [comment] 2023-07-03 11:10
And when enabled packages don't show either?

**Comment by ashes-xda** [comment] 2023-07-03 12:14
yes still no packages (except choco) in installed pkg section

**Comment by Pipixel** [comment] 2023-07-03 12:46
The only way I've found to solve this problem a little is to reset WingetUI, then the installed packages are displayed, but once windows is shut down and booted up nothing is displayed. However, the installer packages are displayed in the package manager logs, but nothing is displayed in the installed packages tab.

Before reset and after system boot: ![image](https://github.com/marticliment/WingetUI/assets/66361896/3641ed86-87c3-4f13-a179-29783d5331a1)

>🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.009997844696044922 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
 Serving Flask app 'WingetUI backend'
 Debug mode: off
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1688384605.5559037]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', 'WingetFound': True, 'WingetVersion': 'v1.4.11071\r'}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4533 result(s)
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
0
🟢 Total packages: 4533
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Reloading Scoop sources...
🟢 Winget packages cached successfuly
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0

After reset and before system shutdown: ![wingetui_n106WLHJDA](https://github.com/marticliment/WingetUI/assets/66361896/51b43dba-cfa7-4a03-803e-bdb215433b70)

>🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.003000497817993164 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
 Serving Flask app 'WingetUI backend'
 Debug mode: off
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1688388042.5009923]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', 'WingetFound': True, 'WingetVersion': 'v1.5.1572\r', 'ChocolateyFound': True, 'ChocolateyVersion': '1.4.0\r'}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🔵 Starting Chocolatey search for available packages
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Winget package caching
🟢 Found valid, non-empty cache file for Chocolatey!
🟢 Winget search for installed packages finished with 4906 result(s)
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 9460 result(s)
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Chocolatey search for installed packages finished with 2 result(s)
🟢 Main application loaded...
0
🟢 Total packages: 9297
🟢 Total packages: 14365
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 162 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 164
🟢 Winget packages cached successfuly
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🔵 Starting Chocolatey search for updates
🔵 Reloading Scoop sources...
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🔵 Reloading Package Manager logs...
🟢 Winget search for updates finished with 50 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 5

**Comment by marticliment** [comment] 2023-07-03 18:56
> However, the installer packages are displayed in the package manager logs, but nothing is displayed in the installed packages tab.
> 
> Before reset and after system boot:

can you please share then Package Manager logs?

**Comment by Pipixel** [comment] 2023-07-03 19:23
all the logs I have are on this pastebin https://pastebin.com/nFEWcX9F

**Comment by ashes-xda** [comment] 2023-07-03 21:44
@Pipixel  @marticliment Are multiple people experiencing this issue, or is it only a few specific cases? I've had this problem in the previous version as well, but I didn't report it because I thought the latest update might have fixed it. However, if it's still persist, then it's a major bug.

**Comment by Pipixel** [comment] 2023-07-03 22:20
I got this bug few days ago, I'm also curious if other users have this issue

**Comment by marticliment** [comment] 2023-07-04 09:46
This bug is random, and seems to happen to a few users only. 
Some of them can fix it by reloading the package list, some of them have only chocolatey packages missing, and for most of the people the installed section works just fine

**Comment by CryptoSiD** [comment] 2024-01-19 11:37
The issue is the file C:\Users\%USERNAME%\AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata is getting corrupted.

Close WingetUI, copy this file from a working installation, and then restart WingetUI and it resolves the issues.

The content of the file should always be as follows:

Sources:
- Name: msstore
  LastUpdate: 1705664097
  DoNotUpdateBefore: 0
  AcceptedAgreementsIdentifier: StoreEdgeFD
  AcceptedAgreementFields: 1
- Name: winget
  LastUpdate: 1705664099
  DoNotUpdateBefore: 0
  AcceptedAgreementsIdentifier:
  AcceptedAgreementFields: 0
- Name: microsoft.builtin.desktop.frameworks
  LastUpdate: 0
  DoNotUpdateBefore: 0
  AcceptedAgreementsIdentifier:
  AcceptedAgreementFields: 0



A check should be added to ensure this file isn't corrupted.

P.S. Excuse my bad English :)

**Comment by Roi-Danton** [comment] 2024-03-29 16:30
Had this issue in the latest version.
Deleting the "C:\Users\%USERNAME%\AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata"  file solved the problem!
Thank you @CryptoSiD

**Comment by BejalKahn** [comment] 2024-05-03 18:22
Thank you @CryptoSiD I solve the problem with your solution!

**Comment by tgschultz** [comment] 2024-05-15 21:37
I can also confirm @CryptoSiD's solution. In my case the file was filled with NUL bytes which, as mentioned previously, is something that I've seen happen after Windows crashes sometimes.
