### ISSUE TITLE
[FEATURE REQUEST] Ability to uninstall packages from the discover packages page

### ISSUE THREAD

**Issue by CallumWatkins** [marticliment/WingetUI#2287] opened 2024-06-05 20:02 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

When viewing the ~~software updates~~ discover packages page, it would be great if the context menu on packages included uninstall options instead of having to switch to the installed packages page.

### Describe how this new feature could help users.

It is unintuitive to right click on a package name and not have the option to uninstall it.

**Comment by marticliment** [comment] 2024-06-05 20:36
This is already a thing, is it not appearing on your device??
![image](https://github.com/marticliment/WingetUI/assets/53119851/fd79836f-9b2c-4ab3-9ed7-f4b0e68d13c5)

**Comment by CallumWatkins** [comment] 2024-06-05 20:48
You're right, I think I meant the discover packages page. When you search for packages and see a package you have installed, there is no option to uninstall it. Sorry for the confusion.

**Comment by marticliment** [comment] 2024-06-05 20:52
duplicate of #1792

**Closed by marticliment** 2024-06-05 20:52 UTC
Labels: new-feature, needs-author-answer
