### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by eidylon** [marticliment/WingetUI#1160] opened 2023-06-22 13:59 UTC
## Before submitting the issue

- [x ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x ] **I have checked that I am running the latest version of WingetUI**
- [x ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Shows a bogus software update where all the fields are header values

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Software Updates'
2. Refresh the list

## Expected behaviour
Don't show the bogus update.

## Screenshots
![wingetui_2023-06-22_09-57-08](https://github.com/marticliment/WingetUI/assets/5951045/98cf05ad-56d1-4d54-9fa8-550623ab0b51)

## The Log

<details>
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
It took 0.012002706527709961 to load all language files
🟢 checkQueue Thread started!
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🔵 Reloading Winget sources...
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Reactivation signal ignored: RaiseWindow_[1687279265.1480682]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', 'WingetFound': True, 'WingetVersion': 'v1.5.1572\r'}
🔵 Reached main ui load milestone
🔵 Is Dark
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🟢 Found valid, non-empty cache file for Winget!
Can't disconnect
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4792 result(s)
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
🟢 Total packages: 4792
🔵 Starting Winget search for updates
🟡 package Entity Framework 6.1.3 Tools  for Vis… failed parsing, going for method 2...
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 349 result(s)
🟢 Winget search for updates finished with 11 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 349
🟠 Package Piriform.CCleaner.ProTrial is legacy blacklisted
🟠 Package Ultimaker.Cura is legacy blacklisted
🟠 Package s is legacy blacklisted
🟡 Package rd is ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 2
🟢 Winget packages cached successfuly
🔵 Reloading Scoop sources...
Win32Mica Error: win32 version 19045 is not supported
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=7-Zip 22.01 (x64), id=7zip.7zip, installId=1687441739.0565243
🔵 Given package: <Package: 7-Zip 22.01 (x64);7zip.7zip;22.01;Winget: winget;<PackageManagers.winget.WingetPackageManager object at 0x000001B6E40090D0>;<genericCustomWidgets.TreeWidgetItemWithQAction object at 0x000001B6E46E8380>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🟡 Icon 7zip-7zip not found in json
🟡 Icon for 7zip.7zip does not exist
🔵 Current program set to 1687441739.0565243
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: 7-Zip 22.01 (x64);7zip.7zip;22.01;Winget: winget;<PackageManagers.winget.WingetPackageManager object at 0x000001B6E40090D0>;<genericCustomWidgets.TreeWidgetItemWithQAction object at 0x000001B6E46E8380>> update with Command ['C:\\Users\\aabdi\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'upgrade', '--id', '7zip.7zip', '--exact', '--include-unknown', '--accept-source-agreements', '--disable-interactivity']
🟡 package Entity Framework 6.1.3 Tools  for Vis… failed parsing, going for method 2...
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 349 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 349
['- \r   \\ \r   | \r                                                                                                                        \r\r  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 14.8 MB\r  ████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 14.8 MB\r  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 14.8 MB\r  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 14.8 MB\r  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 14.8 MB\r  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 14.8 MB\r  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 14.8 MB\r  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  8.00 MB / 14.8 MB\r  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  9.00 MB / 14.8 MB\r  ████████████████████▒▒▒▒▒▒▒▒▒▒  10.0 MB / 14.8 MB\r  ██████████████████████▒▒▒▒▒▒▒▒  11.0 MB / 14.8 MB\r  ████████████████████████▒▒▒▒▒▒  12.0 MB / 14.8 MB\r  ██████████████████████████▒▒▒▒  13.0 MB / 14.8 MB\r  ████████████████████████████▒▒  14.0 MB / 14.8 MB\r  ██████████████████████████████  14.8 MB / 14.8 MB\r                                                                                                                        \r\r   - \r   \\ \r   | \r   / \r   - \r   \\ \r                                                                                                                        \rFound 7-Zip [7zip.7zip] Version 23.01', 'This application is licensed to you by its owner.', 'Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.', 'Downloading https://www.7-zip.org/a/7z2301-x64.exe', '- \r   \\ \r   | \r   / \r                                                                                                                        \r\r                                                                                                                        \r\r  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 1.51 MB\r  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 1.51 MB\r  ██████████████████████████████  1.51 MB / 1.51 MB', 'Successfully verified installer hash', 'Starting package install...', 'The installer will request to run as administrator, expect a prompt.', '- \r   \\ \r   | \r   / \r   - \r   \\ \r   | \r   / \r   - \r   \\ \r   | \r   / \r   - \r   \\ \r   | \r   / \r   - \r   \\ \r                                                                                                                        \rSuccessfully installed', '']
🔵 Reloading Package Manager logs...
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
Win32Mica Error: win32 version 19045 is not supported
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Starting Winget search for updates
🟡 package Entity Framework 6.1.3 Tools  for Vis… failed parsing, going for method 2...
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
🟢 Winget search for installed packages finished with 349 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 349
🔵 Reloading Scoop sources...
🟢 Winget search for updates finished with 68 result(s)
🟠 Package Piriform.CCleaner.ProTrial is legacy blacklisted
🟠 Package Ultimaker.Cura is legacy blacklisted
🟠 Package s is legacy blacklisted
🟡 Package rd is ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 1
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🔵 Loading log...
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
</details>

## Additional context
Tried regetting both the `Winget sources` and the `Winget cache`, no joy.

**Comment by ppvnf** [comment] 2023-06-22 15:18
this seems duplicate of https://github.com/marticliment/WingetUI/issues/1146

**Closed** 2023-06-22 15:27 UTC
Labels: bug, duplicate
