### ISSUE TITLE
[ENHANCEMENT] force to search packages less than 3 char

### ISSUE THREAD

**Issue by pikakolendo02** [marticliment/WingetUI#2209] opened 2024-05-12 15:19 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

<img width="450" alt="image" src="https://github.com/marticliment/WingetUI/assets/15796641/4e34f349-c28e-4593-ae72-239e4f5848db">
Some softwares have a short name less than 3 char. By default I cannot search something less than 3 char. A method like press enter explicit or toggle something in settings is suggested to bypass the limit.
see issues/2186 and issues/2181

### Describe how this improvement could help users.

force to search something less than 3 char

**Comment by marticliment** [comment] 2024-05-13 15:28
Duplicate of #2181

**Closed by marticliment** 2024-05-13 15:28 UTC
Labels: enhancement
