### ISSUE TITLE
[FEATURE REQUEST] Allow multiple downloads while in queue

### ISSUE THREAD

**Issue by rolltidehero** [marticliment/WingetUI#1264] opened 2023-08-04 18:54 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

I think it would save a lot of time if you allowed it do download the packages while they wait in queue to be installed.
Then when it's their turn in the queue, all that it has to do is install since the installer is already downloaded.

### Describe how this new feature could help users.

It will save a lot of time, especially when there are a lot of updates to download and install.

**Comment by marticliment** [comment] 2023-08-09 07:04
duplicate of #1012

**Closed by marticliment** 2023-08-09 07:04 UTC
Labels: new-feature
