### ISSUE TITLE
[FEATURE REQUEST] Filtering on source?

### ISSUE THREAD

**Issue by neslekkim** [marticliment/WingetUI#1070] opened 2023-05-29 10:20 UTC
Is it possible to filter in source?, say you enable all sources, but you don't need to see all the pip packages for one session?
![image](https://github.com/marticliment/WingetUI/assets/281342/80cf0d0e-4105-45bf-be45-cb62422d1657)

**Comment by marticliment** [comment] 2023-05-29 15:28
Duplicate of #584

**Closed** 2023-05-29 15:28 UTC
Labels: feature-request
