### ISSUE TITLE
[ENHANCEMENT] Open file location in context menu

### ISSUE THREAD

**Issue by SilverGreen93** [marticliment/WingetUI#1563] opened 2023-11-15 09:35 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

When right clicking an available update or an installed package, it would be very useful for me to have an option to "Open file location" that will open an Explorer window to the location of the installed application.

I used this feature pretty often in SUMo before.

### Describe how this improvement could help users.

There are cases in which an application can be installed for all users or the current user only. Using this option you can go to the exact location the app is installed and figure out which version is WinGet UI referring to. Also, if there are multiple versions installed, it is also useful to know the location of each.

**Comment by marticliment** [comment] 2023-11-15 15:24
duplicate of #1386

**Closed by marticliment** 2023-11-15 15:24 UTC
Labels: enhancement
