### ISSUE TITLE
[FEATURE REQUEST] Prevent installers from adding shortcuts to the desktop

### ISSUE THREAD

**Issue by tyvsmith** [marticliment/WingetUI#2080] opened 2024-04-03 16:45 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

The feature could work in two ways with option 1 probably be preferrable.

1. Monitor the state of the desktop during installation and if there are new app shortcuts created during an install, potentially with some fuzzy matching, then they are automatically deleted.
2. The tool could switch the Desktop to read only during updates and installs and toggle back when done.

### Describe how this new feature could help users.

One of the most annoying things about software installers on Windows is that the majority take liberty with automatically creating a desktop shortcut and there is no formal way of preventing that. I suggest an experimental feature where WingetUI can help with this when updating/installing through its interface.

**Comment by marticliment** [comment] 2024-04-03 17:01
Duplicate of https://github.com/marticliment/WingetUI/issues/624

**Closed by marticliment** 2024-04-03 17:01 UTC
Labels: new-feature
