### ISSUE TITLE
[BUG] (.NET tool flashes many windows when checking for updates)

### ISSUE THREAD

**Issue by miffe** [marticliment/WingetUI#1762] opened 2024-01-31 13:32 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When the .NET Tool is enabled in the preferences. Every time WingetUI checks for updates it flashes four command windows with the title "%localappdata%\Fork\Update.exe". This only happens when [fork](https://fork.dev) is installed.

Stopping WingetUI or disabling the .NET Tool stops this behavior.

### Steps to reproduce the issue

1. Install fork
2. Start WingetUI with the .NET Tool enabled.
3. Wait for an update check
4. See flashing windows.

### WingetUI Log

```text
https://gist.github.com/miffe/9c8250db81b5e1f76dad973f09b3247e
```

### Package Managers Logs

```text
https://gist.github.com/miffe/8634566f4c650b2ac09e756fbef631e7
```

### Relevant information

WingetUI 2.2.0
Fork 1.93.3.0

Fork issue: fork-dev/TrackerWin#2134

### Screenshots and videos

![300912254-31aca554-5e57-440f-b8ca-41bfad628b99](https://github.com/marticliment/WingetUI/assets/468207/93badfd3-092c-4ef9-82a0-06efc68f96f8)

**Comment by marticliment** [comment] 2024-01-31 14:23
Is fork's update.exe added to the path?

Then the issue is actually with the PowerShell module calling the command `update` to refresh its sources.

**Comment by marticliment** [comment] 2024-01-31 14:24
It is a known bug that has been fixed in source code, but that has not been released yet.

**Comment by miffe** [comment] 2024-01-31 14:27
Yes, forks update.exe is in path.

**Comment by marticliment** [comment] 2024-01-31 14:29
Please try temporarily removing it from path. The issue should not be reproducable then

**Closed** 2024-02-28 14:27 UTC
Labels: bug
