### ISSUE TITLE
[BUG] Problem with Russian symbols

### ISSUE THREAD

**Issue by alabotski** [marticliment/WingetUI#2395] opened 2024-07-03 07:59 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0-beta2

### Windows version, edition and architecture

Windows 11 x64

### Describe your issue

Broken program names are displayed where Cyrillic is present

### UniGetUI Log

```text
[03.07.2024 10:52:07] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0-beta2
[03.07.2024 10:52:07]
[03.07.2024 10:52:07] Version Code:  3,0994
[03.07.2024 10:52:07] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[03.07.2024 10:52:07] Loaded language locale: ru
[03.07.2024 10:52:07] Randomly-generated background API auth token for the current session: gi9ev8ffanxsfer3dorz4pb6fqwd8scj0joyqm7jhts17wagctsiyw6a68f0gihx
[03.07.2024 10:52:07] Api running on http://localhost:7058
[03.07.2024 10:52:07] Command npm was not found on the system
[03.07.2024 10:52:07] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03.07.2024 10:52:08] Lang files were updated successfully from GitHub
[03.07.2024 10:52:08] Downloaded new icons and screenshots successfully!
[03.07.2024 10:52:08] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03.07.2024 10:52:08] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: pip
                      █ Executable path: C:\Users\Aliaksei\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03.07.2024 10:52:08] Running elevated, WinGet class registration is likely to fail
[03.07.2024 10:52:08] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\Aliaksei\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Naive WinGet CLI Version: v1.8.1791
                      █   Microsoft.WinGet.Client PSModule version: 
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03.07.2024 10:52:08] Command scoop was not found on the system
[03.07.2024 10:52:08] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03.07.2024 10:52:09] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Users\Aliaksei\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03.07.2024 10:52:09] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3672                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3672                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03.07.2024 10:52:09] Found 0 available updates from Pip
[03.07.2024 10:52:09] Found 0 installed packages from Pip
[03.07.2024 10:52:10] Dependency WinGet PowerShell Module for manager Winget is present
[03.07.2024 10:52:10] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[03.07.2024 10:52:10] Found 0 available updates from Chocolatey
[03.07.2024 10:52:10] Found 0 installed packages from Chocolatey
[03.07.2024 10:52:11] Found 1 installed packages from PowerShell
[03.07.2024 10:52:11] Found 98 installed packages from Winget
[03.07.2024 10:52:12] Found 0 available updates from Winget
[03.07.2024 10:52:12] Backup saved to D:\Data\Documents\UniGetUI\Установленные пакеты HOME 2024-07-03 10-52-12.json
[03.07.2024 10:52:12] Found 0 available updates from PowerShell
[03.07.2024 10:52:16] Backup saved to D:\Data\Documents\UniGetUI\Установленные пакеты HOME 2024-07-03 10-52-16.json
[03.07.2024 10:53:08] Backup saved to D:\Work\Settings\Windows\UniGetUI\Установленные пакеты HOME 2024-07-03 10-53-08.json
[03.07.2024 10:54:17] Command parse_pip_search.exe was not found on the system
[03.07.2024 10:54:18] Error finding packages on manager Pip with query punto
[03.07.2024 10:54:18] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Не удается найти указанный файл.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 94
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 162
[03.07.2024 10:54:18] Found 1 available packages from Winget with the query punto
[03.07.2024 10:54:19] Found 1 available packages from Chocolatey with the query punto
[03.07.2024 10:54:35] Found 0 available packages from PowerShell with the query punto
[03.07.2024 10:54:38] Command parse_pip_search.exe was not found on the system
[03.07.2024 10:54:38] Error finding packages on manager Pip with query upnote
[03.07.2024 10:54:38] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Не удается найти указанный файл.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 94
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 162
[03.07.2024 10:54:38] Found 1 available packages from Winget with the query upnote
[03.07.2024 10:54:39] Found 0 available packages from Chocolatey with the query upnote
[03.07.2024 10:54:56] Found 0 available packages from PowerShell with the query upnote
[03.07.2024 10:54:59] Command parse_pip_search.exe was not found on the system
[03.07.2024 10:54:59] Error finding packages on manager Pip with query SingularityApp
[03.07.2024 10:54:59] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Не удается найти указанный файл.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 94
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 162
[03.07.2024 10:54:59] Found 0 available packages from Winget with the query SingularityApp
[03.07.2024 10:55:00] Found 2 available packages from Chocolatey with the query SingularityApp
[03.07.2024 10:55:01] Found 0 available packages from Winget with the query SingularityApp
[03.07.2024 10:55:01] Command parse_pip_search.exe was not found on the system
[03.07.2024 10:55:02] Error finding packages on manager Pip with query SingularityApp
[03.07.2024 10:55:02] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Не удается найти указанный файл.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 94
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 162
[03.07.2024 10:55:02] Found 2 available packages from Chocolatey with the query SingularityApp
[03.07.2024 10:55:17] Found 0 available packages from PowerShell with the query SingularityApp
[03.07.2024 10:55:20] Found 0 available packages from PowerShell with the query SingularityApp
[03.07.2024 10:55:55] Uninstall
[03.07.2024 10:55:55] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[03.07.2024 10:55:55] Icon for package ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_Display.Driver was not found, returning default icon
[03.07.2024 10:55:55] Found 0 screenshots for package Id=ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_Display.Driver
[03.07.2024 10:55:55] Loaded details for package ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_Display.Driver on manager Winget
[03.07.2024 10:56:03] Uninstall
[03.07.2024 10:56:03] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[03.07.2024 10:56:03] Icon for package MSIX\Microsoft.LanguageExperiencePackru-RU_22621.56.222.0_neutral__8wekyb3d8bbwe was not found, returning default icon
[03.07.2024 10:56:03] Found 0 screenshots for package Id=MSIX\Microsoft.LanguageExperiencePackru-RU_22621.56.222.0_neutral__8wekyb3d8bbwe
[03.07.2024 10:56:03] Loaded details for package MSIX\Microsoft.LanguageExperiencePackru-RU_22621.56.222.0_neutral__8wekyb3d8bbwe on manager Winget
[03.07.2024 10:57:44] Uninstall
[03.07.2024 10:57:44] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[03.07.2024 10:57:44] Icon for package ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_Display.Driver was not found, returning default icon
[03.07.2024 10:57:44] Found 0 screenshots for package Id=ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_Display.Driver
[03.07.2024 10:57:49] Uninstall
[03.07.2024 10:57:49] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[03.07.2024 10:57:49] Icon for package ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_HDAudio.Driver was not found, returning default icon
[03.07.2024 10:57:49] Found 0 screenshots for package Id=ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_HDAudio.Driver
[03.07.2024 10:57:49] Loaded details for package ARP\Machine\X64\{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}_HDAudio.Driver on manager Winget
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 03.07.2024 10:52:08
Process end time:   03.07.2024 10:52:08

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Aliaksei\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 03.07.2024 10:52:09
Process end time:   03.07.2024 10:52:10

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03.07.2024 10:52:09
Process end time:   03.07.2024 10:52:11

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : ��� "﻿Write-Output" �� �ᯮ����� ��� ��� ���������, �㭪樨, 䠩�� �業��� ��� �믮��塞�� �ண�
  ����. �஢���� �ࠢ��쭮��� ����ᠭ�� �����, � ⠪�� ����稥 � �ࠢ��쭮��� ���, ��᫥ 祣� ������ ������.
  ��ப�:1 ����:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 03.07.2024 10:52:09
Process end time:   03.07.2024 10:52:09

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03.07.2024 10:52:10
Process end time:   03.07.2024 10:52:12

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : ��� "﻿Write-Output" �� �ᯮ����� ��� ��� ���������, �㭪樨, 䠩�� �業��� ��� �믮��塞�� �ண�
  ����. �஢���� �ࠢ��쭮��� ����ᠭ�� �����, � ⠪�� ����稥 � �ࠢ��쭮��� ���, ��᫥ 祣� ������ ������.
  ��ப�:1 ����:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 03.07.2024 10:54:17
Process end time:   03.07.2024 10:54:18

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 03.07.2024 10:54:38
Process end time:   03.07.2024 10:54:38

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 03.07.2024 10:54:58
Process end time:   03.07.2024 10:54:59

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 03.07.2024 10:55:01
Process end time:   03.07.2024 10:55:01

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageDetails
Process start time: 03.07.2024 10:55:55
Process end time:   03.07.2024 10:55:55

-- Task errors
  Failed to get catalog Microsoft Store. Is the package local?

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 03.07.2024 10:55:55
Process end time:   03.07.2024 10:55:55

-- Task errors
  Failed to get catalog Microsoft Store. Is the package local?

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageDetails
Process start time: 03.07.2024 10:56:03
Process end time:   03.07.2024 10:56:03

-- Task errors
  Failed to get catalog Этот ПК. Is the package local?

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 03.07.2024 10:56:03
Process end time:   03.07.2024 10:56:03

-- Task errors
  Failed to get catalog Этот ПК. Is the package local?

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 03.07.2024 10:57:44
Process end time:   03.07.2024 10:57:44

-- Task errors
  Failed to get catalog Microsoft Store. Is the package local?

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageDetails
Process start time: 03.07.2024 10:57:49
Process end time:   03.07.2024 10:57:49

-- Task errors
  Failed to get catalog Microsoft Store. Is the package local?

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 03.07.2024 10:57:49
Process end time:   03.07.2024 10:57:49

-- Task errors
  Failed to get catalog Microsoft Store. Is the package local?

The task reported a failure (1)

——————————————————————————————————————————
```

### Screenshots and videos

[2024-07-03 10 56 10](https://github.com/marticliment/WingetUI/assets/439337/79b82826-2341-4d5f-b835-91f2e110027e)
[2024-07-03 10 57 46](https://github.com/marticliment/WingetUI/assets/439337/e232f034-e395-441d-8ff4-a072385dc617)
[2024-07-03 10 57 51](https://github.com/marticliment/WingetUI/assets/439337/d862a23d-0ea1-4a79-a3de-6a5419111071)

**Comment by marticliment** [comment] 2024-07-03 08:18
Duplicate of #2242

**Closed by marticliment** 2024-07-03 08:18 UTC
Labels: bug

**Comment by marticliment** [comment] 2024-07-05 23:16
Hello,

To all users facing issues with version 3.1.0, please try the new 3.1.1 beta, which aims to fix this issues.

UniGetUI 3.1.1-beta0 release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1-beta0
Direct installer URL: https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta0/UniGetUI.Installer.exe

Excuse me for the inconveniences.

**Comment by alabotski** [comment] 2024-07-06 15:33
@marticliment Thank you

When will there be a new version for installation via WinGet?
UniGetUI (formerly WingetUI)                                       ARP\Machine\X86\{889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1          3.1.0-beta2

**Comment by marticliment** [comment] 2024-07-06 17:07
Yes, the file is being published. 

@alabotski, does it fix the issue?
