### ISSUE TITLE
[FEATURE REQUEST] show installation date of packages

### ISSUE THREAD

**Issue by Kamilcuk** [marticliment/WingetUI#2078] opened 2024-04-03 07:33 UTC
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

When browsing existing installed packages, show a column with installation date, and allow to sort by newest or oldest.

### Describe how this new feature could help users.

I sometimes install packages for testing. Sorting by installation date, i can quickly spot viruses, temporary installations and unwanted packages. I use this with the builtin windows "add or remove programs" view in settings.

Unigetui is amazing.

**Comment by marticliment** [comment] 2024-04-03 11:10
Duplicate of #22
Duplicate of #1157

**Closed by marticliment** 2024-04-03 11:10 UTC
Labels: new-feature
